"""GIF 생성기 템플릿 시드 48종.

만든 방법
--------
`애니메이션18종-추천조합표.md`의 조합 원칙을 코드로 옮겨 생성했다.
  · 회전 계열(스핀·셔플·킥업·롤인)은 외곽선이 두꺼운 효과만 쓴다
    — 글자가 기울어진 채 지나가서 외곽선이 없으면 경계가 뭉갠다
  · 슬램·셔플에는 네온을 쓰지 않는다 — 잔상이 많아 투명 GIF의 64색을 넘긴다
  · 시네마틱 2종은 청첩장·감성 문구에만, 금속 계열 효과와 함께
  · 허브마다 8개씩, 애니메이션 18종을 모두 최소 한 번은 쓴다

비율·위치에 대하여
------------------
48종 전부 16:9 · 중앙정렬이다. 비율과 세로 위치를 섞어두면 목록에서
칸마다 글자 크기가 제각각으로 보이고, 어차피 사용자가 비율을 바꾸면
다시 잡히므로 기준을 하나로 둔다. 비율은 편집기에서 언제든 바꿀 수 있다.

글자 크기(font.size)에 대하여
----------------------------
손으로 정하지 않았다. 브라우저에서 운영 폰트 파일을 실제로 로드해
measureText로 재고, 문구 폭이 캔버스의 80%가 되도록 계산한 값이다.
한글을 1em으로 어림하면 손글씨체는 너무 작고 장식체는 넘친다.
size는 canvas.w×canvas.h에서 정한 값이고, 다른 비율로 바꾸면
gif-render.js의 sizePx()가 좁아지는 쪽 배율로 환산한다.

폰트 id는 운영 DB 기준이다. 없는 id는 시드에서 건너뛰고 로그를 남긴다.
"""

GIF_TEMPLATE_SEED_VERSION = "2"

GIF_TEMPLATES = [

    # ── 유튜브 썸네일 ──────────────────────────────
    {'number': '001', 'title': '슬램 임팩트', 'hub_slug': 'thumbnail', 'anim': 'slamImpact', 'anim_category': 'dynamic', 'effect': 'bold-outline', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 62, 'font_weight': 800, 'sample_text': '오늘만 이 가격', 'config': {'sampleText': '오늘만 이 가격', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 62, 'weight': 800, 'size': 80, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'bold-outline', 'animation': {'type': 'slamImpact', 'inDuration': 0.9, 'total': 2.2, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 10},
    {'number': '002', 'title': '줌 인', 'hub_slug': 'thumbnail', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'cherry', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 17, 'font_weight': 800, 'sample_text': '역대급 혜택이 왔다', 'config': {'sampleText': '역대급 혜택이 왔다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 17, 'weight': 800, 'size': 77, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'cherry', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 20},
    {'number': '003', 'title': '타이핑', 'hub_slug': 'thumbnail', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 63, 'font_weight': 800, 'sample_text': '이걸 몰랐다고?', 'config': {'sampleText': '이걸 몰랐다고?', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 63, 'weight': 800, 'size': 95, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 30},
    {'number': '004', 'title': '네온 점멸', 'hub_slug': 'thumbnail', 'anim': 'neonFlicker', 'anim_category': 'basic', 'effect': 'neon-orange', 'ratio': '16:9', 'gif_rating': 1, 'font_id': 17, 'font_weight': 800, 'sample_text': '긴급 공지드립니다', 'config': {'sampleText': '긴급 공지드립니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 17, 'weight': 800, 'size': 92, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'neon-orange', 'animation': {'type': 'neonFlicker', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#C2410C', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 40},
    {'number': '005', 'title': '킥업', 'hub_slug': 'thumbnail', 'anim': 'kickUp', 'anim_category': 'dynamic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 11, 'font_weight': 400, 'sample_text': '지금 바로 확인', 'config': {'sampleText': '지금 바로 확인', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 11, 'weight': 400, 'size': 101, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'kickUp', 'inDuration': 1.0, 'total': 2.2, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 50},
    {'number': '006', 'title': '글자 팝', 'hub_slug': 'thumbnail', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'comic', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 76, 'font_weight': 400, 'sample_text': '충격 실화', 'config': {'sampleText': '충격 실화', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 76, 'weight': 400, 'size': 153, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'comic', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 60},
    {'number': '007', 'title': '스핀 인', 'hub_slug': 'thumbnail', 'anim': 'spinIn', 'anim_category': 'dynamic', 'effect': 'bold-outline', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 172, 'font_weight': 700, 'sample_text': '새로운 시작이다', 'config': {'sampleText': '새로운 시작이다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 172, 'weight': 700, 'size': 96, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'bold-outline', 'animation': {'type': 'spinIn', 'inDuration': 1.2, 'total': 2.4, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 70},
    {'number': '008', 'title': '하이라이트', 'hub_slug': 'thumbnail', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 155, 'font_weight': 800, 'sample_text': '3일 만에 조회수 100만', 'config': {'sampleText': '3일 만에 조회수 100만', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 155, 'weight': 800, 'size': 69, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDE047', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 80},

    # ── 브이로그 자막 ──────────────────────────────
    {'number': '009', 'title': '슬라이드 업', 'hub_slug': 'vlog', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 162, 'font_weight': 400, 'sample_text': '오늘의 브이로그', 'config': {'sampleText': '오늘의 브이로그', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 162, 'weight': 400, 'size': 96, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 90},
    {'number': '010', 'title': '타이핑', 'hub_slug': 'vlog', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 12, 'font_weight': 400, 'sample_text': '아침 7시, 커피부터', 'config': {'sampleText': '아침 7시, 커피부터', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 12, 'weight': 400, 'size': 121, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 100},
    {'number': '011', 'title': '마스크 와이프', 'hub_slug': 'vlog', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'double-line', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 156, 'font_weight': 400, 'sample_text': '드디어 도착했습니다', 'config': {'sampleText': '드디어 도착했습니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 156, 'weight': 400, 'size': 75, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'double-line', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 110},
    {'number': '012', 'title': '하이라이트', 'hub_slug': 'vlog', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 173, 'font_weight': 400, 'sample_text': '이 집 진짜 맛있어요', 'config': {'sampleText': '이 집 진짜 맛있어요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 173, 'weight': 400, 'size': 80, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDBA74', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 120},
    {'number': '013', 'title': '글자 팝', 'hub_slug': 'vlog', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'candy', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 143, 'font_weight': 800, 'sample_text': '기다리던 주말', 'config': {'sampleText': '기다리던 주말', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 143, 'weight': 800, 'size': 111, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'candy', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#DB2777', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 130},
    {'number': '014', 'title': '글자 회전', 'hub_slug': 'vlog', 'anim': 'flip', 'anim_category': 'basic', 'effect': 'sky-blue', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 168, 'font_weight': 400, 'sample_text': '관점을 바꾸면', 'config': {'sampleText': '관점을 바꾸면', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 168, 'weight': 400, 'size': 111, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'sky-blue', 'animation': {'type': 'flip', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 140},
    {'number': '015', 'title': '단어 교체', 'hub_slug': 'vlog', 'anim': 'wordSwap', 'anim_category': 'basic', 'effect': 'classic-white', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 149, 'font_weight': 700, 'sample_text': '아침 / 점심 / 저녁', 'config': {'sampleText': '아침 / 점심 / 저녁', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 149, 'weight': 700, 'size': 89, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-white', 'animation': {'type': 'wordSwap', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 150},
    {'number': '016', 'title': '슬라이드 업', 'hub_slug': 'vlog', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 151, 'font_weight': 400, 'sample_text': '천천히 걸어도 괜찮아', 'config': {'sampleText': '천천히 걸어도 괜찮아', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 151, 'weight': 400, 'size': 73, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 160},

    # ── 인스타 · 카드뉴스 ──────────────────────────────
    {'number': '017', 'title': '하이라이트', 'hub_slug': 'card', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 170, 'font_weight': 700, 'sample_text': '핵심만 정리했습니다', 'config': {'sampleText': '핵심만 정리했습니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 170, 'weight': 700, 'size': 75, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': '#FDE047', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 170},
    {'number': '018', 'title': '단어 교체', 'hub_slug': 'card', 'anim': 'wordSwap', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 1, 'font_weight': 700, 'sample_text': '기획 / 디자인 / 개발', 'config': {'sampleText': '기획 / 디자인 / 개발', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 1, 'weight': 700, 'size': 71, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'wordSwap', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 180},
    {'number': '019', 'title': '슬라이드 업', 'hub_slug': 'card', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'midnight', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 7, 'font_weight': 400, 'sample_text': '알아두면 좋은 5가지', 'config': {'sampleText': '알아두면 좋은 5가지', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 7, 'weight': 400, 'size': 79, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'midnight', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#93C5FD', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 190},
    {'number': '020', 'title': '타이핑', 'hub_slug': 'card', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 158, 'font_weight': 400, 'sample_text': '3분이면 끝나는\n서류 정리법', 'config': {'sampleText': '3분이면 끝나는\n서류 정리법', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 158, 'weight': 400, 'size': 99, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 200},
    {'number': '021', 'title': '글자 팝', 'hub_slug': 'card', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 42, 'font_weight': 700, 'sample_text': '저장 필수', 'config': {'sampleText': '저장 필수', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 42, 'weight': 700, 'size': 153, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 210},
    {'number': '022', 'title': '마스크 와이프', 'hub_slug': 'card', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'double-line', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 58, 'font_weight': 400, 'sample_text': '잘 정리된 하루', 'config': {'sampleText': '잘 정리된 하루', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 58, 'weight': 400, 'size': 109, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'double-line', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 220},
    {'number': '023', 'title': '줌 인', 'hub_slug': 'card', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'midnight', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 160, 'font_weight': 700, 'sample_text': '본질에만 집중하기', 'config': {'sampleText': '본질에만 집중하기', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 160, 'weight': 700, 'size': 74, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'midnight', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#93C5FD', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 230},
    {'number': '024', 'title': '글자 회전', 'hub_slug': 'card', 'anim': 'flip', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 76, 'font_weight': 400, 'sample_text': '완전히 달라집니다', 'config': {'sampleText': '완전히 달라집니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 76, 'weight': 400, 'size': 81, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'flip', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 240},

    # ── 청첩장 · 초대장 ──────────────────────────────
    {'number': '025', 'title': '시네마틱', 'hub_slug': 'wedding', 'anim': 'cinematicTrack', 'anim_category': 'cinematic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 156, 'font_weight': 400, 'sample_text': '저희 결혼합니다', 'config': {'sampleText': '저희 결혼합니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 156, 'weight': 400, 'size': 77, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'cinematicTrack', 'inDuration': 2.0, 'total': 4.5, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 250},
    {'number': '026', 'title': '골드 스윕', 'hub_slug': 'wedding', 'anim': 'shineSweep', 'anim_category': 'cinematic', 'effect': 'golden', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 59, 'font_weight': 400, 'sample_text': '함께해 주세요', 'config': {'sampleText': '함께해 주세요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 59, 'weight': 400, 'size': 107, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'golden', 'animation': {'type': 'shineSweep', 'inDuration': 1.4, 'total': 4.0, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#7A5C00', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 260},
    {'number': '027', 'title': '마스크 와이프', 'hub_slug': 'wedding', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 33, 'font_weight': 400, 'sample_text': '귀한 걸음 부탁드립니다', 'config': {'sampleText': '귀한 걸음 부탁드립니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 33, 'weight': 400, 'size': 62, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 270},
    {'number': '028', 'title': '슬라이드 업', 'hub_slug': 'wedding', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 72, 'font_weight': 400, 'sample_text': '2026년 5월 16일\n토요일 낮 12시', 'config': {'sampleText': '2026년 5월 16일\n토요일 낮 12시', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 72, 'weight': 400, 'size': 90, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'none', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 280},
    {'number': '029', 'title': '시네마틱', 'hub_slug': 'wedding', 'anim': 'cinematicTrack', 'anim_category': 'cinematic', 'effect': 'gold-grad', 'ratio': '16:9', 'gif_rating': 1, 'font_id': 82, 'font_weight': 400, 'sample_text': '다시 만나는 계절', 'config': {'sampleText': '다시 만나는 계절', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 82, 'weight': 400, 'size': 73, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'gold-grad', 'animation': {'type': 'cinematicTrack', 'inDuration': 2.0, 'total': 4.5, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#92400E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 290},
    {'number': '030', 'title': '타이핑', 'hub_slug': 'wedding', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 22, 'font_weight': 400, 'sample_text': '작은 마음을 전합니다', 'config': {'sampleText': '작은 마음을 전합니다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 22, 'weight': 400, 'size': 70, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 300},
    {'number': '031', 'title': '골드 스윕', 'hub_slug': 'wedding', 'anim': 'shineSweep', 'anim_category': 'cinematic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 8, 'font_weight': 400, 'sample_text': '평생을 약속하며', 'config': {'sampleText': '평생을 약속하며', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 8, 'weight': 400, 'size': 93, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'shineSweep', 'inDuration': 1.4, 'total': 4.0, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 310},
    {'number': '032', 'title': '줌 인', 'hub_slug': 'wedding', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 34, 'font_weight': 400, 'sample_text': '오래 기다린 날', 'config': {'sampleText': '오래 기다린 날', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 34, 'weight': 400, 'size': 84, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 320},

    # ── 감성 문구 ──────────────────────────────
    {'number': '033', 'title': '시네마틱', 'hub_slug': 'quote', 'anim': 'cinematicTrack', 'anim_category': 'cinematic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 154, 'font_weight': 400, 'sample_text': '봄날의 산책', 'config': {'sampleText': '봄날의 산책', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 154, 'weight': 400, 'size': 106, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'cinematicTrack', 'inDuration': 2.0, 'total': 4.5, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 330},
    {'number': '034', 'title': '타이핑', 'hub_slug': 'quote', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 151, 'font_weight': 400, 'sample_text': '오늘도 수고했어', 'config': {'sampleText': '오늘도 수고했어', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 151, 'weight': 400, 'size': 96, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 340},
    {'number': '035', 'title': '슬라이드 업', 'hub_slug': 'quote', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 66, 'font_weight': 400, 'sample_text': '지나고 나면\n다 괜찮아질 거야', 'config': {'sampleText': '지나고 나면\n다 괜찮아질 거야', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 66, 'weight': 400, 'size': 99, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'classic-black', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 350},
    {'number': '036', 'title': '마스크 와이프', 'hub_slug': 'quote', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 65, 'font_weight': 400, 'sample_text': '덜어낼수록 선명해진다', 'config': {'sampleText': '덜어낼수록 선명해진다', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 65, 'weight': 400, 'size': 89, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 360},
    {'number': '037', 'title': '하이라이트', 'hub_slug': 'quote', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 67, 'font_weight': 400, 'sample_text': '기억하고 싶은 순간', 'config': {'sampleText': '기억하고 싶은 순간', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 67, 'weight': 400, 'size': 115, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#F9A8D4', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 370},
    {'number': '038', 'title': '글자 팝', 'hub_slug': 'quote', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'rose-pink', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 77, 'font_weight': 400, 'sample_text': '작은 행복 하나', 'config': {'sampleText': '작은 행복 하나', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 77, 'weight': 400, 'size': 119, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'rose-pink', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 380},
    {'number': '039', 'title': '슬라이드 업', 'hub_slug': 'quote', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 161, 'font_weight': 400, 'sample_text': '다시 그 거리에서', 'config': {'sampleText': '다시 그 거리에서', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 161, 'weight': 400, 'size': 93, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 390},
    {'number': '040', 'title': '시네마틱', 'hub_slug': 'quote', 'anim': 'cinematicTrack', 'anim_category': 'cinematic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 6, 'font_weight': 400, 'sample_text': '조용한 오후의 햇살', 'config': {'sampleText': '조용한 오후의 햇살', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 6, 'weight': 400, 'size': 104, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'cinematicTrack', 'inDuration': 2.0, 'total': 4.5, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 400},

    # ── 굿즈 · 스티커 ──────────────────────────────
    {'number': '041', 'title': '고무줄', 'hub_slug': 'goods', 'anim': 'elasticStretch', 'anim_category': 'dynamic', 'effect': 'candy', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 175, 'font_weight': 300, 'sample_text': '말랑말랑 부드럽게', 'config': {'sampleText': '말랑말랑 부드럽게', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 175, 'weight': 300, 'size': 84, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'candy', 'animation': {'type': 'elasticStretch', 'inDuration': 1.4, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#DB2777', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 410},
    {'number': '042', 'title': '롤인', 'hub_slug': 'goods', 'anim': 'rollIn', 'anim_category': 'dynamic', 'effect': 'comic', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 143, 'font_weight': 800, 'sample_text': '데굴데굴 굴러와요', 'config': {'sampleText': '데굴데굴 굴러와요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 143, 'weight': 800, 'size': 84, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'comic', 'animation': {'type': 'rollIn', 'inDuration': 1.3, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 420},
    {'number': '043', 'title': '킥업', 'hub_slug': 'goods', 'anim': 'kickUp', 'anim_category': 'dynamic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 95, 'font_weight': 400, 'sample_text': '힘차게 시작하자', 'config': {'sampleText': '힘차게 시작하자', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 95, 'weight': 400, 'size': 95, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'kickUp', 'inDuration': 1.0, 'total': 2.2, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 430},
    {'number': '044', 'title': '글자 팝', 'hub_slug': 'goods', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'candy', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 168, 'font_weight': 400, 'sample_text': '오늘도 화이팅', 'config': {'sampleText': '오늘도 화이팅', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 168, 'weight': 400, 'size': 111, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'candy', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#DB2777', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 440},
    {'number': '045', 'title': '바운스 드롭', 'hub_slug': 'goods', 'anim': 'bounceDrop', 'anim_category': 'basic', 'effect': 'lavender', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 24, 'font_weight': 400, 'sample_text': '통통 튀는 하루', 'config': {'sampleText': '통통 튀는 하루', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 24, 'weight': 400, 'size': 144, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lavender', 'animation': {'type': 'bounceDrop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6D28D9', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 450},
    {'number': '046', 'title': '스핀 인', 'hub_slug': 'goods', 'anim': 'spinIn', 'anim_category': 'dynamic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 39, 'font_weight': 700, 'sample_text': '좋아요 꾹', 'config': {'sampleText': '좋아요 꾹', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 39, 'weight': 700, 'size': 153, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'spinIn', 'inDuration': 1.2, 'total': 2.4, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 460},
    {'number': '047', 'title': '셔플', 'hub_slug': 'goods', 'anim': 'shuffleIn', 'anim_category': 'dynamic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 102, 'font_weight': 400, 'sample_text': '흩어진 조각 모으기', 'config': {'sampleText': '흩어진 조각 모으기', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 102, 'weight': 400, 'size': 106, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'shuffleIn', 'inDuration': 1.2, 'total': 2.4, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 470},
    {'number': '048', 'title': '고무줄', 'hub_slug': 'goods', 'anim': 'elasticStretch', 'anim_category': 'dynamic', 'effect': 'mint', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 48, 'font_weight': 400, 'sample_text': '탱글탱글 젤리처럼', 'config': {'sampleText': '탱글탱글 젤리처럼', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 48, 'weight': 400, 'size': 118, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'mint', 'animation': {'type': 'elasticStretch', 'inDuration': 1.4, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#0F766E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 480},
]
