"""GIF 생성기 템플릿 시드 50종 — 용도 5종 × 문구 10개.

문구
----
운영자가 직접 정한 50문장이다. 긴 문장에만 줄바꿈을 넣었다.
문구를 고치는 곳은 이 파일이 아니라 어드민(/admin/gif)이다 —
여기를 고쳐도 이미 시드된 DB는 바뀌지 않는다.

조합 원칙 (`애니메이션18종-추천조합표.md`)
  · 회전 계열(스핀·셔플·킥업·롤인)은 외곽선이 두꺼운 효과만 쓴다
    — 글자가 기울어진 채 지나가서 외곽선이 없으면 경계가 뭉갠다
  · 슬램·셔플에는 네온을 쓰지 않는다 — 잔상이 많아 투명 GIF의 64색을 넘긴다
  · 시네마틱 2종은 감성·인사에만, 금속 계열 효과와 함께
  · 회전·슬램·단어교체는 1줄만
  · 용도마다 10개씩, 애니메이션 18종을 모두 최소 한 번은 쓴다

비율·위치에 대하여
------------------
50종 전부 16:9 · 중앙정렬이다. 비율과 세로 위치를 섞어두면 목록에서
칸마다 글자 크기가 제각각으로 보이고, 어차피 사용자가 비율을 바꾸면
다시 잡히므로 기준을 하나로 둔다. 비율은 편집기에서 언제든 바꿀 수 있다.

글자 크기(font.size)에 대하여
----------------------------
손으로 정하지 않았다. 브라우저에서 운영 폰트 파일을 실제로 로드해
measureText로 재고, 문구 폭이 캔버스의 80%가 되도록 계산한 값이다.
한글을 1em으로 어림하면 손글씨체는 너무 작고 장식체는 넘친다.
단어 교체(wordSwap)만은 한 번에 한 단어씩 보이므로 가장 긴 '단어'로 쟀다.
size는 canvas.w×canvas.h에서 정한 값이고, 다른 비율로 바꾸면
gif-render.js의 sizePx()가 좁아지는 쪽 배율로 환산한다.

폰트 id는 운영 DB 기준이고, 전부 app/gif_use_case_data.py의 해당 용도
목록 안에 있다. 없는 id는 시드에서 건너뛰고 로그를 남긴다.
"""

GIF_TEMPLATE_SEED_VERSION = "3"

GIF_TEMPLATES = [

    # ── 일상 — 브이로그 자막 · 하루 기록 ──────────────────────────
    {'number': '001', 'title': '하이라이트', 'hub_slug': 'daily', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 162, 'font_weight': 400, 'sample_text': '오늘도 무사히 칼퇴 성공', 'config': {'sampleText': '오늘도 무사히 칼퇴 성공', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 162, 'weight': 400, 'size': 64, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDE047', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 10},
    {'number': '002', 'title': '마스크 와이프', 'hub_slug': 'daily', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'double-line', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 173, 'font_weight': 400, 'sample_text': '소소하지만 확실한 행복', 'config': {'sampleText': '소소하지만 확실한 행복', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 173, 'weight': 400, 'size': 66, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'double-line', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 20},
    {'number': '003', 'title': '글자 팝', 'hub_slug': 'daily', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'candy', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 143, 'font_weight': 800, 'sample_text': '이것이 바로 주말의 맛', 'config': {'sampleText': '이것이 바로 주말의 맛', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 143, 'weight': 800, 'size': 80, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'candy', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#DB2777', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 30},
    {'number': '004', 'title': '바운스 드롭', 'hub_slug': 'daily', 'anim': 'bounceDrop', 'anim_category': 'basic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 153, 'font_weight': 400, 'sample_text': '소중한 내 휴일 돌려줘', 'config': {'sampleText': '소중한 내 휴일 돌려줘', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 153, 'weight': 400, 'size': 89, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'bounceDrop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 40},
    {'number': '005', 'title': '타이핑', 'hub_slug': 'daily', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 12, 'font_weight': 400, 'sample_text': '오늘 하루도 수고했어', 'config': {'sampleText': '오늘 하루도 수고했어', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 12, 'weight': 400, 'size': 121, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 50},
    {'number': '006', 'title': '줌 인', 'hub_slug': 'daily', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'mint', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 168, 'font_weight': 400, 'sample_text': '맛있는 거 옆에 맛있는 거', 'config': {'sampleText': '맛있는 거 옆에 맛있는 거', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 168, 'weight': 400, 'size': 51, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'mint', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#0F766E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 60},
    {'number': '007', 'title': '단어 교체', 'hub_slug': 'daily', 'anim': 'wordSwap', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 149, 'font_weight': 700, 'sample_text': '이게 바로 삶의 이유', 'config': {'sampleText': '이게 바로 삶의 이유', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 149, 'weight': 700, 'size': 153, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'wordSwap', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 70},
    {'number': '008', 'title': '글자 회전', 'hub_slug': 'daily', 'anim': 'flip', 'anim_category': 'basic', 'effect': 'sky-blue', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 4, 'font_weight': 400, 'sample_text': '일단 누워서 생각하자', 'config': {'sampleText': '일단 누워서 생각하자', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 4, 'weight': 400, 'size': 78, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'sky-blue', 'animation': {'type': 'flip', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 80},
    {'number': '009', 'title': '슬라이드 업', 'hub_slug': 'daily', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 156, 'font_weight': 400, 'sample_text': '소소한 일상의 기록', 'config': {'sampleText': '소소한 일상의 기록', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 156, 'weight': 400, 'size': 82, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 90},
    {'number': '010', 'title': '고무줄', 'hub_slug': 'daily', 'anim': 'elasticStretch', 'anim_category': 'dynamic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 151, 'font_weight': 400, 'sample_text': '오늘도 알차게\n흘러가는 하루', 'config': {'sampleText': '오늘도 알차게\n흘러가는 하루', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 151, 'weight': 400, 'size': 107, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'vintage', 'animation': {'type': 'elasticStretch', 'inDuration': 1.4, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 100},

    # ── 인사 — 안부 · 인사말 · 소통 ────────────────────────────
    {'number': '011', 'title': '글자 팝', 'hub_slug': 'greeting', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 161, 'font_weight': 400, 'sample_text': '좋은 아침! 오늘도 파이팅', 'config': {'sampleText': '좋은 아침! 오늘도 파이팅', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 161, 'weight': 400, 'size': 77, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 110},
    {'number': '012', 'title': '하이라이트', 'hub_slug': 'greeting', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 66, 'font_weight': 400, 'sample_text': '맛점하세요 여러분', 'config': {'sampleText': '맛점하세요 여러분', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 66, 'weight': 400, 'size': 115, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDBA74', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 120},
    {'number': '013', 'title': '타이핑', 'hub_slug': 'greeting', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 65, 'font_weight': 400, 'sample_text': '오늘 하루도 고생 많았어요', 'config': {'sampleText': '오늘 하루도 고생 많았어요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 65, 'weight': 400, 'size': 76, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 130},
    {'number': '014', 'title': '슬라이드 업', 'hub_slug': 'greeting', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'midnight', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 67, 'font_weight': 400, 'sample_text': '모두 따뜻하고\n편안한 밤 되세요', 'config': {'sampleText': '모두 따뜻하고\n편안한 밤 되세요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 67, 'weight': 400, 'size': 107, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'midnight', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#93C5FD', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 140},
    {'number': '015', 'title': '바운스 드롭', 'hub_slug': 'greeting', 'anim': 'bounceDrop', 'anim_category': 'basic', 'effect': 'rose-pink', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 77, 'font_weight': 400, 'sample_text': '반가워요! 자주 소통해요', 'config': {'sampleText': '반가워요! 자주 소통해요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 77, 'weight': 400, 'size': 73, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'rose-pink', 'animation': {'type': 'bounceDrop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 150},
    {'number': '016', 'title': '마스크 와이프', 'hub_slug': 'greeting', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 6, 'font_weight': 400, 'sample_text': '주말 잘 보내고 계신가요?', 'config': {'sampleText': '주말 잘 보내고 계신가요?', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 6, 'weight': 400, 'size': 91, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 160},
    {'number': '017', 'title': '골드 스윕', 'hub_slug': 'greeting', 'anim': 'shineSweep', 'anim_category': 'cinematic', 'effect': 'golden', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 87, 'font_weight': 400, 'sample_text': '즐거운 연휴 보내세요', 'config': {'sampleText': '즐거운 연휴 보내세요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 87, 'weight': 400, 'size': 117, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'golden', 'animation': {'type': 'shineSweep', 'inDuration': 1.4, 'total': 4.0, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#7A5C00', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 170},
    {'number': '018', 'title': '줌 인', 'hub_slug': 'greeting', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 154, 'font_weight': 400, 'sample_text': '오랜만에 전하는 안부', 'config': {'sampleText': '오랜만에 전하는 안부', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 154, 'weight': 400, 'size': 73, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 180},
    {'number': '019', 'title': '글자 회전', 'hub_slug': 'greeting', 'anim': 'flip', 'anim_category': 'basic', 'effect': 'sky-blue', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 34, 'font_weight': 400, 'sample_text': '오늘도 들러주셔서 감사해요', 'config': {'sampleText': '오늘도 들러주셔서 감사해요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 34, 'weight': 400, 'size': 50, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'sky-blue', 'animation': {'type': 'flip', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 190},
    {'number': '020', 'title': '슬라이드 업', 'hub_slug': 'greeting', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'candy', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 187, 'font_weight': 400, 'sample_text': '내일 또 만나요', 'config': {'sampleText': '내일 또 만나요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 187, 'weight': 400, 'size': 124, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'candy', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#DB2777', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 200},

    # ── 감성 — 분위기 · 생각 · 센치함 ───────────────────────────
    {'number': '021', 'title': '시네마틱', 'hub_slug': 'mood', 'anim': 'cinematicTrack', 'anim_category': 'cinematic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 59, 'font_weight': 400, 'sample_text': '바람마저 완벽했던 오늘', 'config': {'sampleText': '바람마저 완벽했던 오늘', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 59, 'weight': 400, 'size': 51, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'cinematicTrack', 'inDuration': 2.0, 'total': 4.5, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 210},
    {'number': '022', 'title': '타이핑', 'hub_slug': 'mood', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 33, 'font_weight': 400, 'sample_text': '글자로 다 담지 못할 분위기', 'config': {'sampleText': '글자로 다 담지 못할 분위기', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 33, 'weight': 400, 'size': 54, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 220},
    {'number': '023', 'title': '슬라이드 업', 'hub_slug': 'mood', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 156, 'font_weight': 400, 'sample_text': '조용히 마음을\n채우는 시간', 'config': {'sampleText': '조용히 마음을\n채우는 시간', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 156, 'weight': 400, 'size': 107, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'vintage', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 230},
    {'number': '024', 'title': '마스크 와이프', 'hub_slug': 'mood', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'silver', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 72, 'font_weight': 400, 'sample_text': '계절이 넘어가는 소리', 'config': {'sampleText': '계절이 넘어가는 소리', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 72, 'weight': 400, 'size': 70, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'silver', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6B7280', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 240},
    {'number': '025', 'title': '줌 인', 'hub_slug': 'mood', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'gold-grad', 'ratio': '16:9', 'gif_rating': 2, 'font_id': 82, 'font_weight': 400, 'sample_text': '어쩌면 가장 예쁜 순간', 'config': {'sampleText': '어쩌면 가장 예쁜 순간', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 82, 'weight': 400, 'size': 62, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'gold-grad', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#92400E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 250},
    {'number': '026', 'title': '골드 스윕', 'hub_slug': 'mood', 'anim': 'shineSweep', 'anim_category': 'cinematic', 'effect': 'golden', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 175, 'font_weight': 300, 'sample_text': '지친 마음에 건네는 위로', 'config': {'sampleText': '지친 마음에 건네는 위로', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 175, 'weight': 300, 'size': 76, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'golden', 'animation': {'type': 'shineSweep', 'inDuration': 1.4, 'total': 4.0, 'fps': 15}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#7A5C00', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 260},
    {'number': '027', 'title': '글자 회전', 'hub_slug': 'mood', 'anim': 'flip', 'anim_category': 'basic', 'effect': 'vintage', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 89, 'font_weight': 400, 'sample_text': '따뜻한 공기, 완벽한 온도', 'config': {'sampleText': '따뜻한 공기, 완벽한 온도', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 89, 'weight': 400, 'size': 70, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'vintage', 'animation': {'type': 'flip', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#5C3D1E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 270},
    {'number': '028', 'title': '글자 팝', 'hub_slug': 'mood', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'lavender', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 168, 'font_weight': 400, 'sample_text': '선물 같은 하루를\n선물받은 기분', 'config': {'sampleText': '선물 같은 하루를\n선물받은 기분', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 168, 'weight': 400, 'size': 85, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'lavender', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#6D28D9', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 280},
    {'number': '029', 'title': '바운스 드롭', 'hub_slug': 'mood', 'anim': 'bounceDrop', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 55, 'font_weight': 400, 'sample_text': '천천히 흘러가도 괜찮아', 'config': {'sampleText': '천천히 흘러가도 괜찮아', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 55, 'weight': 400, 'size': 76, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'bounceDrop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 290},
    {'number': '030', 'title': '하이라이트', 'hub_slug': 'mood', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 167, 'font_weight': 700, 'sample_text': '마음이 차분해지는 순간', 'config': {'sampleText': '마음이 차분해지는 순간', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 167, 'weight': 700, 'size': 67, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#C4B5FD', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 300},

    # ── 상세페이지 · 이벤트 — 판매 · 홍보 · 썸네일 ───────────────────
    {'number': '031', 'title': '줌 인', 'hub_slug': 'promo', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'bold-outline', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 62, 'font_weight': 800, 'sample_text': '실물 보고 감탄한 핏', 'config': {'sampleText': '실물 보고 감탄한 핏', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 62, 'weight': 800, 'size': 64, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'bold-outline', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 310},
    {'number': '032', 'title': '타이핑', 'hub_slug': 'promo', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 17, 'font_weight': 800, 'sample_text': '입자마자 분위기 완성', 'config': {'sampleText': '입자마자 분위기 완성', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 17, 'weight': 800, 'size': 79, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 320},
    {'number': '033', 'title': '슬라이드 업', 'hub_slug': 'promo', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'cherry', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 63, 'font_weight': 800, 'sample_text': '문의 폭주했던\n바로 그 아이템', 'config': {'sampleText': '문의 폭주했던\n바로 그 아이템', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 63, 'weight': 800, 'size': 101, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'cherry', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 330},
    {'number': '034', 'title': '마스크 와이프', 'hub_slug': 'promo', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 1, 'font_weight': 700, 'sample_text': '재입고 요청 1위!\n드디어 오픈', 'config': {'sampleText': '재입고 요청 1위!\n드디어 오픈', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 1, 'weight': 700, 'size': 90, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'lemon', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 340},
    {'number': '035', 'title': '슬램 임팩트', 'hub_slug': 'promo', 'anim': 'slamImpact', 'anim_category': 'dynamic', 'effect': 'bold-outline', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 155, 'font_weight': 800, 'sample_text': '주목해주세요!', 'config': {'sampleText': '주목해주세요!', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 155, 'weight': 800, 'size': 78, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'bold-outline', 'animation': {'type': 'slamImpact', 'inDuration': 0.9, 'total': 2.2, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 350},
    {'number': '036', 'title': '하이라이트', 'hub_slug': 'promo', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 172, 'font_weight': 700, 'sample_text': '지갑 열리게 만드는 비주얼', 'config': {'sampleText': '지갑 열리게 만드는 비주얼', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 172, 'weight': 700, 'size': 55, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDE047', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 360},
    {'number': '037', 'title': '네온 점멸', 'hub_slug': 'promo', 'anim': 'neonFlicker', 'anim_category': 'basic', 'effect': 'neon-orange', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 75, 'font_weight': 900, 'sample_text': '오늘만 이 가격, 한정 수량', 'config': {'sampleText': '오늘만 이 가격, 한정 수량', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 75, 'weight': 900, 'size': 62, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'neon-orange', 'animation': {'type': 'neonFlicker', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#C2410C', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 370},
    {'number': '038', 'title': '고무줄', 'hub_slug': 'promo', 'anim': 'elasticStretch', 'anim_category': 'dynamic', 'effect': 'comic', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 76, 'font_weight': 400, 'sample_text': '입어보면\n다른 이유를 알아요', 'config': {'sampleText': '입어보면\n다른 이유를 알아요', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 76, 'weight': 400, 'size': 79, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'comic', 'animation': {'type': 'elasticStretch', 'inDuration': 1.4, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 380},
    {'number': '039', 'title': '킥업', 'hub_slug': 'promo', 'anim': 'kickUp', 'anim_category': 'dynamic', 'effect': 'bold-outline', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 164, 'font_weight': 400, 'sample_text': '매일 손이 가는 데일리템', 'config': {'sampleText': '매일 손이 가는 데일리템', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 164, 'weight': 400, 'size': 62, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'bold-outline', 'animation': {'type': 'kickUp', 'inDuration': 1.0, 'total': 2.2, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 390},
    {'number': '040', 'title': '셔플', 'hub_slug': 'promo', 'anim': 'shuffleIn', 'anim_category': 'dynamic', 'effect': 'comic', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 11, 'font_weight': 400, 'sample_text': '고민은 배송만 늦출 뿐', 'config': {'sampleText': '고민은 배송만 늦출 뿐', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 11, 'weight': 400, 'size': 67, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'comic', 'animation': {'type': 'shuffleIn', 'inDuration': 1.2, 'total': 2.4, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 400},

    # ── 블로그 · SNS — 후기 · 카드뉴스 · 정보 정리 ─────────────────
    {'number': '041', 'title': '하이라이트', 'hub_slug': 'sns', 'anim': 'highlight', 'anim_category': 'basic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 170, 'font_weight': 700, 'sample_text': '솔직하게 적어보는 내돈내산 후기', 'config': {'sampleText': '솔직하게 적어보는 내돈내산 후기', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 170, 'weight': 700, 'size': 46, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'highlight', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': '#FDE047', 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 410},
    {'number': '042', 'title': '타이핑', 'hub_slug': 'sns', 'anim': 'typewriter', 'anim_category': 'basic', 'effect': 'none', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 7, 'font_weight': 400, 'sample_text': '나만 알고 싶은 은밀한 맛집', 'config': {'sampleText': '나만 알고 싶은 은밀한 맛집', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 7, 'weight': 400, 'size': 60, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'none', 'animation': {'type': 'typewriter', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#111111', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 420},
    {'number': '043', 'title': '슬라이드 업', 'hub_slug': 'sns', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'mint', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 160, 'font_weight': 700, 'sample_text': '일상 속 작은 힐링 모음집', 'config': {'sampleText': '일상 속 작은 힐링 모음집', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 160, 'weight': 700, 'size': 66, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'mint', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#0F766E', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 430},
    {'number': '044', 'title': '마스크 와이프', 'hub_slug': 'sns', 'anim': 'wipe', 'anim_category': 'basic', 'effect': 'double-line', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 158, 'font_weight': 400, 'sample_text': '이번 주 일상 털이 시작', 'config': {'sampleText': '이번 주 일상 털이 시작', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 158, 'weight': 400, 'size': 67, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'double-line', 'animation': {'type': 'wipe', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 440},
    {'number': '045', 'title': '글자 팝', 'hub_slug': 'sns', 'anim': 'pop', 'anim_category': 'basic', 'effect': 'lemon', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 42, 'font_weight': 700, 'sample_text': '직접 써보고 추천하는 꿀템', 'config': {'sampleText': '직접 써보고 추천하는 꿀템', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 42, 'weight': 700, 'size': 66, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'lemon', 'animation': {'type': 'pop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#A16207', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 450},
    {'number': '046', 'title': '줌 인', 'hub_slug': 'sns', 'anim': 'zoomIn', 'anim_category': 'basic', 'effect': 'midnight', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 180, 'font_weight': 700, 'sample_text': '알차게 다녀온\n주말 데이트 코스', 'config': {'sampleText': '알차게 다녀온\n주말 데이트 코스', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 180, 'weight': 700, 'size': 85, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.3}, 'effect': 'midnight', 'animation': {'type': 'zoomIn', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#93C5FD', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 460},
    {'number': '047', 'title': '스핀 인', 'hub_slug': 'sns', 'anim': 'spinIn', 'anim_category': 'dynamic', 'effect': 'classic-black', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 1, 'font_weight': 700, 'sample_text': '실패 없는 조합 추천', 'config': {'sampleText': '실패 없는 조합 추천', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 1, 'weight': 700, 'size': 75, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'classic-black', 'animation': {'type': 'spinIn', 'inDuration': 1.2, 'total': 2.4, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 470},
    {'number': '048', 'title': '바운스 드롭', 'hub_slug': 'sns', 'anim': 'bounceDrop', 'anim_category': 'basic', 'effect': 'cherry', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 173, 'font_weight': 400, 'sample_text': '오늘의 착장 (OOTD)', 'config': {'sampleText': '오늘의 착장 (OOTD)', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 173, 'weight': 400, 'size': 75, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'cherry', 'animation': {'type': 'bounceDrop', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#FFFFFF', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 480},
    {'number': '049', 'title': '롤인', 'hub_slug': 'sns', 'anim': 'rollIn', 'anim_category': 'dynamic', 'effect': 'comic', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 149, 'font_weight': 700, 'sample_text': '놓치면 후회하는 핵심 포인트', 'config': {'sampleText': '놓치면 후회하는 핵심 포인트', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 149, 'weight': 700, 'size': 56, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'comic', 'animation': {'type': 'rollIn', 'inDuration': 1.3, 'total': 2.6, 'fps': 24}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#000000', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 490},
    {'number': '050', 'title': '슬라이드 업', 'hub_slug': 'sns', 'anim': 'slideUp', 'anim_category': 'basic', 'effect': 'retro', 'ratio': '16:9', 'gif_rating': 3, 'font_id': 16, 'font_weight': 400, 'sample_text': '소소하지만 알찬 팁 공유', 'config': {'sampleText': '소소하지만 알찬 팁 공유', 'canvas': {'w': 800, 'h': 450, 'ratio': '16:9'}, 'font': {'id': 16, 'weight': 400, 'size': 74, 'baseW': 800, 'baseH': 450, 'lineHeight': 1.2}, 'effect': 'retro', 'animation': {'type': 'slideUp', 'inDuration': 1.5, 'total': 2.5, 'fps': 20}, 'bg': None, 'photo': None, 'matteAuto': True, 'matte': '#78350F', 'highlight': None, 'layout': {'posY': 0.5}}, 'is_active': True, 'sort_order': 500},
]
