"""폰트 페어링 시드 데이터 v4 (신규 8테마 추가 + 문구 다양화 + 폰트풀 확장)

- PAIRING_SEED_VERSION이 바뀌면 seed.py가 기존 시드를 지우고 재삽입
- 이름 기준으로 DB 폰트와 매칭, 없는 폰트 조합은 자동 스킵
- 어드민 페어링 관리(2단계) 도입 후에는 버전을 올리지 말 것 (수동 데이터 보호)
"""

PAIRING_SEED_VERSION = "4"

PAIRING_SEED = [{'id': 1,
  'theme': '유튜브 썸네일',
  'title_font_name': '검은고딕',
  'body_font_name': '프리텐다드',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '이벤트 상세는 고정 댓글 확인하세요',
  'description': '가장 두꺼운 검은고딕이 시선을 잡고, 프리텐다드가 부제를 담백하게 받쳐줍니다.'},
 {'id': 2,
  'theme': '유튜브 썸네일',
  'title_font_name': 'SB어그로체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '이 가격에 이게 된다고?',
  'sample_body': '직접 써보고 놀란 이유 5가지',
  'description': '어그로체 특유의 임팩트에 나눔스퀘어의 단정함이 균형을 만듭니다.'},
 {'id': 3,
  'theme': '유튜브 썸네일',
  'title_font_name': '티몬 몬소리체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '한 달 만에 확 달라졌어요',
  'sample_body': '전후 비교 영상 지금 공개합니다',
  'description': '몬소리체의 개성 있는 두께감과 노토산스의 무난한 가독성 조합.'},
 {'id': 4,
  'theme': '유튜브 썸네일',
  'title_font_name': '서울로',
  'body_font_name': '수트',
  'sample_title': '절대 하지 마세요',
  'sample_body': '99%가 모르는 진짜 이유',
  'description': '서울로의 꽉 찬 임팩트와 수트의 모던한 부제 — 도시적인 썸네일 조합.'},
 {'id': 5,
  'theme': '유튜브 썸네일',
  'title_font_name': '경기천년제목',
  'body_font_name': '서울알림체',
  'sample_title': '아무도 안 알려주는 꿀팁',
  'sample_body': '저만 알고 싶었던 정보예요',
  'description': '경기천년제목의 묵직한 존재감을 서울알림체가 깔끔하게 받쳐줍니다.'},
 {'id': 6,
  'theme': '유튜브 썸네일',
  'title_font_name': '열정도체',
  'body_font_name': '프리텐다드',
  'sample_title': '실화입니다',
  'sample_body': '믿기지 않겠지만 전부 사실이에요',
  'description': '열정도체의 뜨거운 획과 프리텐다드의 차분한 부제 — 강렬한 대비.'},
 {'id': 7,
  'theme': '유튜브 썸네일',
  'title_font_name': '이누아리두리네',
  'body_font_name': '수트',
  'sample_title': '처음 공개하는 비하인드',
  'sample_body': '촬영 뒷이야기 풀버전',
  'description': '이누아리두리네의 압도적인 두께를 수트가 깔끔하게 정리합니다.'},
 {'id': 8,
  'theme': '유튜브 썸네일',
  'title_font_name': '이사만루체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '7일 챌린지 결과',
  'sample_body': '매일 기록한 리얼 변화',
  'description': '이사만루체의 스포츠 임팩트와 노토산스의 안정감.'},
 {'id': 9,
  'theme': '유튜브 썸네일',
  'title_font_name': '원스토어 모바일고딕 제목체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '이거 하나면 끝',
  'sample_body': '더 이상 헤매지 마세요',
  'description': '원스토어 제목체의 또렷한 획과 나눔스퀘어의 단정한 부제.'},
 {'id': 10,
  'theme': '유튜브 썸네일',
  'title_font_name': '와일드각',
  'body_font_name': '프리텐다드',
  'sample_title': '솔직 후기 남깁니다',
  'sample_body': '장단점 가감 없이 말씀드려요',
  'description': '와일드각의 날카로운 개성에 프리텐다드의 균형감.'},
 {'id': 11,
  'theme': '유튜브 썸네일',
  'title_font_name': '던파 비트비트체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '충격 반전 결말',
  'sample_body': '끝까지 보시면 압니다',
  'description': '비트비트체의 게임 감성과 노토산스의 무난함 — 게임·리뷰 채널용.'},
 {'id': 12,
  'theme': '유튜브 썸네일',
  'title_font_name': '세방고딕',
  'body_font_name': '수트',
  'sample_title': '제작비 얼마 들었을까',
  'sample_body': '예산 공개 리얼 브이로그',
  'description': '세방고딕의 클래식한 굵기와 수트의 현대적인 부제.'},
 {'id': 13,
  'theme': '유튜브 썸네일',
  'title_font_name': '태나다체',
  'body_font_name': '프리텐다드',
  'sample_title': '첫 방송 풀버전',
  'sample_body': '떨렸던 그날의 기록',
  'description': '태나다체의 독특한 존재감을 프리텐다드가 받쳐줍니다.'},
 {'id': 14,
  'theme': '유튜브 썸네일',
  'title_font_name': 'HS산토끼체',
  'body_font_name': '고운돋움',
  'sample_title': '구독자 질문 총정리',
  'sample_body': '가장 많이 물어보신 것들 답변드려요',
  'description': '산토끼체의 통통 튀는 매력과 고운돋움의 부드러움.'},
 {'id': 15,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '여기어때 잘난체',
  'body_font_name': 'KoPub돋움',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '잘난체의 친근한 볼륨감과 KoPub돋움의 안정적인 본문 가독성.'},
 {'id': 16,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '에스코어드림',
  'body_font_name': '나눔스퀘어',
  'sample_title': '아침 10분 루틴',
  'sample_body': '하루가 달라지는 작은 습관을 소개합니다.',
  'description': '에스코어드림 굵은 웨이트로 제목, 나눔스퀘어로 본문 — 정보성 카드뉴스의 정석.'},
 {'id': 17,
  'theme': '카드뉴스 · SNS',
  'title_font_name': 'G마켓 산스',
  'body_font_name': '프리텐다드',
  'sample_title': '알아두면 쓸모있는 생활 정보',
  'sample_body': '몰랐던 지원금부터 할인 혜택까지 한 번에 정리.',
  'description': 'G마켓 산스와 프리텐다드, 둘 다 화면용으로 설계돼 어떤 주제든 무난합니다.'},
 {'id': 18,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '푸른숲체',
  'body_font_name': '수트',
  'sample_title': '요즘 뜨는 동네 카페 5곳',
  'sample_body': '주말 나들이 코스로 딱이에요.',
  'description': '푸른숲체의 자연스러운 제목과 수트의 정돈된 본문 — 공익·환경 콘텐츠에 잘 맞습니다.'},
 {'id': 19,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '리아체',
  'body_font_name': '고운돋움',
  'sample_title': '면접 전 꼭 확인할 3가지',
  'sample_body': '합격률을 높이는 작은 디테일.',
  'description': '리아체의 통통 튀는 임팩트를 고운돋움이 부드럽게 중화해 줍니다.'},
 {'id': 20,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '창원단감아삭체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '반려동물 초보 가이드',
  'sample_body': '처음 키우는 분들을 위한 필수 체크리스트.',
  'description': '단감아삭체의 아삭한 개성과 노토산스의 정돈된 본문.'},
 {'id': 21,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '평창평화체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '퇴근 후 30분 운동법',
  'sample_body': '헬스장 안 가도 집에서 충분해요.',
  'description': '평화체의 부드러운 곡선과 나눔스퀘어의 단정함.'},
 {'id': 22,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '하남다움체',
  'body_font_name': '수트',
  'sample_title': '여름 휴가지 추천 BEST',
  'sample_body': '가성비부터 감성 숙소까지 모았습니다.',
  'description': '하남다움체의 도시적인 제목과 수트의 모던한 본문.'},
 {'id': 23,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '카페24 아네모네',
  'body_font_name': '고운돋움',
  'sample_title': '자취생 필수템 리스트',
  'sample_body': '이사할 때 꼭 챙겨야 할 물건들.',
  'description': '아네모네의 감성적인 곡선과 고운돋움의 차분한 본문.'},
 {'id': 24,
  'theme': '카드뉴스 · SNS',
  'title_font_name': 'Y너만을 비춤체',
  'body_font_name': '프리텐다드',
  'sample_title': '건강검진 결과 이렇게 읽으세요',
  'sample_body': '숫자만 봐선 모르는 진짜 의미.',
  'description': '비춤체의 반짝이는 개성과 프리텐다드의 안정감.'},
 {'id': 25,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '배달의민족 주아체',
  'body_font_name': '마루부리',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '주아체의 붓 터치 느낌과 마루부리의 부드러운 명조가 손맛을 살립니다.'},
 {'id': 26,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '카페24 써라운드',
  'body_font_name': '아리따 부리',
  'sample_title': '오늘의 원두',
  'sample_body': '에티오피아 예가체프, 산미가 좋은 하루.',
  'description': '써라운드의 둥근 제목과 아리따 부리의 우아한 본문 — 브랜드 무드에 적합.'},
 {'id': 27,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '티머니 둥근바람',
  'body_font_name': '고운바탕',
  'sample_title': '작은 가게의 큰 정성',
  'sample_body': '하나하나 손으로 만듭니다.',
  'description': '둥근바람의 몽글몽글한 제목과 고운바탕의 잔잔한 명조 본문.'},
 {'id': 28,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '낭만있구미체',
  'body_font_name': '갬성명조',
  'sample_title': '창가 자리가 좋은 계절',
  'sample_body': '햇살 드는 오후, 책 한 권과 커피.',
  'description': '낭만있구미체의 레트로 굴림과 갬성명조의 손글씨 감성 — 이름 그대로 낭만 조합.'},
 {'id': 29,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '땅스부대찌개',
  'body_font_name': '제주명조',
  'sample_title': '매일 아침 굽는 소보로',
  'sample_body': '오전 11시 오픈, 다 팔리면 마감이에요.',
  'description': '부대찌개체의 통통한 개성과 제주명조의 차분함이 대비를 만듭니다.'},
 {'id': 30,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '카페24 클랙식타입',
  'body_font_name': '나눔명조',
  'sample_title': '느리게 걷는 골목길 카페',
  'sample_body': '도심 속 작은 쉼표가 되어드릴게요.',
  'description': '클랙식타입의 빈티지한 획과 나눔명조의 클래식함 — 레트로 브랜딩.'},
 {'id': 31,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': 'HS산토끼체',
  'body_font_name': '고운바탕',
  'sample_title': '향기로 기억되는 곳',
  'sample_body': '문을 열면 퍼지는 갓 내린 커피 향.',
  'description': '산토끼체의 귀여운 제목과 고운바탕의 담백한 본문.'},
 {'id': 32,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '빙그레싸만코체',
  'body_font_name': '마루부리',
  'sample_title': '단골이 되고 싶은 가게',
  'sample_body': '오늘도 변함없는 그 자리에서.',
  'description': '싸만코체의 말랑한 제목과 마루부리의 온화한 본문.'},
 {'id': 33,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 을지로체',
  'body_font_name': '나눔명조',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '을지로체의 레트로 간판 감성과 나눔명조의 신뢰감 있는 본문.'},
 {'id': 34,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 한나체',
  'body_font_name': 'KoPub바탕',
  'sample_title': '주민센터 휴관 안내',
  'sample_body': '시설 점검으로 3월 15일 하루 휴관합니다.',
  'description': '한나체의 투박한 매력을 KoPub바탕이 차분하게 정리해줍니다.'},
 {'id': 35,
  'theme': '포스터 · 안내문',
  'title_font_name': 'MBC1961',
  'body_font_name': '을유1945',
  'sample_title': '봄맞이 대청소 캠페인',
  'sample_body': '4월 첫째 주, 우리 동네가 함께합니다.',
  'description': 'MBC1961의 옛 방송 자막 느낌과 을유1945 — 레트로 무드 완성 조합.'},
 {'id': 36,
  'theme': '포스터 · 안내문',
  'title_font_name': '워헤이븐',
  'body_font_name': '수트',
  'sample_title': '무료 건강검진 실시',
  'sample_body': '만 40세 이상 주민 대상, 사전 접수 필수.',
  'description': '워헤이븐의 독특한 세리프 제목과 수트의 모던 고딕 — 대비가 만드는 긴장감.'},
 {'id': 37,
  'theme': '포스터 · 안내문',
  'title_font_name': '웃맨체',
  'body_font_name': '고운바탕',
  'sample_title': '작은 음악회 초대합니다',
  'sample_body': '5월 20일 저녁, 마을회관 앞마당에서.',
  'description': '웃맨체의 개성 있는 획과 고운바탕의 단정함, 전시·행사 포스터용.'},
 {'id': 38,
  'theme': '포스터 · 안내문',
  'title_font_name': '을지로 10년후 체',
  'body_font_name': '나눔명조',
  'sample_title': '분리배출 안내문',
  'sample_body': '올바른 배출 방법을 다시 한 번 확인해 주세요.',
  'description': '을지로 10년후 체의 바랜 감성과 나눔명조의 진중함 — 전시 포스터에 좋습니다.'},
 {'id': 39,
  'theme': '포스터 · 안내문',
  'title_font_name': '케리스 케듀체',
  'body_font_name': '서울알림체',
  'sample_title': '여름방학 특별 프로그램',
  'sample_body': '초등학생 대상 진로 체험 교실을 운영합니다.',
  'description': '케듀체의 또렷한 제목과 서울알림체의 정보 전달력 — 교육 안내문용.'},
 {'id': 40,
  'theme': '포스터 · 안내문',
  'title_font_name': '학교안심 둥근미소',
  'body_font_name': 'KoPub돋움',
  'sample_title': '주차장 이용 안내',
  'sample_body': '공사 기간 중 임시 주차장을 이용해 주세요.',
  'description': '둥근미소의 친근한 제목과 KoPub돋움의 안정적인 본문 — 학교·기관 안내문.'},
 {'id': 41,
  'theme': '포스터 · 안내문',
  'title_font_name': '강원교육모두',
  'body_font_name': '나눔스퀘어',
  'sample_title': '사진 공모전 접수 시작',
  'sample_body': '우리 동네 풍경을 담아주세요, 시상식은 9월.',
  'description': '강원교육모두의 반듯한 손글씨와 나눔스퀘어의 정돈된 본문.'},
 {'id': 42,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '상상토끼 꽃길',
  'body_font_name': '부크크 명조',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '꽃길체의 붓글씨 제목에 부크크 명조의 잔잔한 본문이 어울립니다.'},
 {'id': 43,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '잉크립퀴드',
  'body_font_name': '마루부리',
  'sample_title': '괜찮아, 잘 하고 있어',
  'sample_body': '조급해하지 않아도 돼요.',
  'description': '잉크립퀴드의 강한 붓 획과 마루부리의 온화함 — 강약 대비가 좋습니다.'},
 {'id': 44,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '쿨가이체',
  'body_font_name': '고운돋움',
  'sample_title': '봄날처럼 따스하게',
  'sample_body': '작은 행복이 가득한 하루 되세요.',
  'description': '쿨가이체의 시원한 캘리 획을 고운돋움이 차분하게 받쳐줍니다.'},
 {'id': 45,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '정묵바위체',
  'body_font_name': '을유1945',
  'sample_title': '당신을 응원합니다',
  'sample_body': '지금 이 순간도 충분히 잘하고 있어요.',
  'description': '정묵바위체의 묵직한 붓글씨와 을유1945의 고전미.'},
 {'id': 46,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '그리운 경찰감성체',
  'body_font_name': '고운바탕',
  'sample_title': '마음에 새기는 한마디',
  'sample_body': '천천히, 그러나 꾸준히.',
  'description': '경찰감성체의 그리운 손글씨와 고운바탕의 담백함.'},
 {'id': 47,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '정선아리랑체',
  'body_font_name': '나눔명조',
  'sample_title': '오늘 하루도 감사히',
  'sample_body': '평범한 일상이 실은 가장 소중해요.',
  'description': '정선아리랑체의 유려한 획과 나눔명조의 단정함.'},
 {'id': 48,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '완도희망체',
  'body_font_name': '마루부리',
  'sample_title': '바람이 전하는 안부',
  'sample_body': '멀리서도 마음은 늘 함께예요.',
  'description': '완도희망체의 힘 있는 붓글씨와 마루부리의 부드러움.'},
 {'id': 49,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '신비는 일곱살',
  'body_font_name': '나눔스퀘어',
  'sample_title': '네 덕분에 웃는다',
  'sample_body': '고마운 사람에게 전하는 짧은 편지.',
  'description': '신비는 일곱살의 아이 손글씨와 나눔스퀘어의 깔끔함.'},
 {'id': 50,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '이서윤체',
  'body_font_name': '프리텐다드',
  'sample_title': '별처럼 빛나기를',
  'sample_body': '지금의 노력이 헛되지 않을 거예요.',
  'description': '이서윤체의 단정한 손글씨와 프리텐다드의 현대적인 본문.'},
 {'id': 51,
  'theme': '브이로그 자막',
  'title_font_name': '귀욤뭉이',
  'body_font_name': '수트',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '귀욤뭉이의 몽글한 손글씨 자막과 수트의 깔끔한 정보 자막 조합.'},
 {'id': 52,
  'theme': '브이로그 자막',
  'title_font_name': '빙그레체',
  'body_font_name': '고운돋움',
  'sample_title': '주말 데이트 코스',
  'sample_body': '맛집 투어부터 카페 나들이까지 기록했어요.',
  'description': '빙그레체의 명랑한 제목 자막과 고운돋움의 잔잔한 서브 자막.'},
 {'id': 53,
  'theme': '브이로그 자막',
  'title_font_name': '사진관',
  'body_font_name': '서울알림체',
  'sample_title': '혼자 떠난 1박 2일',
  'sample_body': '아무 계획 없이 훌쩍 다녀왔어요.',
  'description': '사진관체의 손글씨 감성과 서울알림체의 또렷한 정보 전달력.'},
 {'id': 54,
  'theme': '브이로그 자막',
  'title_font_name': '온글잎 콘콘체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '오늘 저녁 메뉴는',
  'sample_body': '냉장고 파먹기 브이로그, 레시피는 댓글에.',
  'description': '콘콘체의 귀여운 손글씨와 나눔스퀘어의 깔끔함 — 다이어리 무드.'},
 {'id': 55,
  'theme': '브이로그 자막',
  'title_font_name': '바른생활',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '집콕 하루 기록',
  'sample_body': '아무것도 안 해도 충분히 좋은 하루.',
  'description': '바른생활체의 또박또박한 자막과 노토산스의 안정감.'},
 {'id': 56,
  'theme': '브이로그 자막',
  'title_font_name': '갬성명조',
  'body_font_name': '수트',
  'sample_title': '이사 준비 첫날',
  'sample_body': '짐 정리부터 시작하는 새 시작.',
  'description': '갬성명조의 감성 자막과 수트의 담백한 정보 자막.'},
 {'id': 57,
  'theme': '브이로그 자막',
  'title_font_name': '다이어리체',
  'body_font_name': '프리텐다드',
  'sample_title': '출근 전 모닝 루틴',
  'sample_body': '30분 일찍 일어나서 달라진 것들.',
  'description': '다이어리체의 아기자기함과 프리텐다드의 깔끔함.'},
 {'id': 58,
  'theme': '브이로그 자막',
  'title_font_name': '오뮤 다예쁨체',
  'body_font_name': '고운돋움',
  'sample_title': '반려견과 함께한 산책',
  'sample_body': '동네 한 바퀴, 오늘도 신났어요.',
  'description': '다예쁨체의 예쁜 손글씨와 고운돋움의 차분함.'},
 {'id': 59,
  'theme': '브이로그 자막',
  'title_font_name': '온글잎 긍정',
  'body_font_name': '나눔스퀘어',
  'sample_title': '처음 해보는 홈베이킹',
  'sample_body': '실패해도 재밌는 도전기.',
  'description': '온글잎 긍정의 밝은 손글씨와 나눔스퀘어의 정돈됨.'},
 {'id': 60,
  'theme': '브이로그 자막',
  'title_font_name': '교보손글씨 2019',
  'body_font_name': '수트',
  'sample_title': '퇴사 후 첫 여행',
  'sample_body': '설레는 마음으로 떠난 그 순간.',
  'description': '교보손글씨의 따뜻함과 수트의 모던한 정보 자막.'},
 {'id': 61,
  'theme': '브이로그 자막',
  'title_font_name': '교보손글씨 이유빈체',
  'body_font_name': '고운돋움',
  'sample_title': '장보기 브이로그',
  'sample_body': '오늘 산 재료로 뭘 만들어볼까요.',
  'description': '이유빈체의 귀여운 손글씨와 고운돋움의 부드러움.'},
 {'id': 62,
  'theme': '브이로그 자막',
  'title_font_name': '둘기마요고딕',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '운동 시작한 지 30일',
  'sample_body': '작심삼일 없이 버틴 기록.',
  'description': '둘기마요고딕의 동글동글함과 노토산스의 무난함.'},
 {'id': 63,
  'theme': '브이로그 자막',
  'title_font_name': '카페 24 쑥쑥',
  'body_font_name': '서울알림체',
  'sample_title': '친구와의 티타임',
  'sample_body': '수다 떨며 보낸 여유로운 오후.',
  'description': '쑥쑥체의 아이 같은 손글씨와 서울알림체의 또렷함.'},
 {'id': 64,
  'theme': '브이로그 자막',
  'title_font_name': '학교안심 받아쓰기',
  'body_font_name': 'KoPub돋움',
  'sample_title': '책상 정리하는 날',
  'sample_body': '작은 변화가 주는 큰 만족감.',
  'description': '받아쓰기체의 또박또박함과 KoPub돋움의 안정적인 자막.'},
 {'id': 65,
  'theme': '포인트 서체 조합',
  'title_font_name': 'Y최애체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '최애체의 개성 있는 포인트와 노토산스의 담백한 본문.'},
 {'id': 66,
  'theme': '포인트 서체 조합',
  'title_font_name': 'Y클로버체',
  'body_font_name': '수트',
  'sample_title': '한 끗 다른 느낌',
  'sample_body': '포인트 서체 하나로 완전히 달라지는 무드.',
  'description': '클로버체의 러블리한 포인트와 수트의 모던함.'},
 {'id': 67,
  'theme': '포인트 서체 조합',
  'title_font_name': '배달의민족 꾸불림체',
  'body_font_name': '프리텐다드',
  'sample_title': '강조하고 싶은 단어',
  'sample_body': '눈에 띄어야 할 곳엔 확실하게.',
  'description': '꾸불림체의 유쾌한 곡선과 프리텐다드의 균형감.'},
 {'id': 68,
  'theme': '포인트 서체 조합',
  'title_font_name': '빛의계승자체',
  'body_font_name': 'KoPub바탕',
  'sample_title': '제목만 바꿔도 달라져요',
  'sample_body': '같은 문장, 다른 인상.',
  'description': '빛의계승자체의 판타지 감성과 KoPub바탕의 진중함.'},
 {'id': 69,
  'theme': '포인트 서체 조합',
  'title_font_name': '카페24 모야모야',
  'body_font_name': '나눔스퀘어',
  'sample_title': '시선을 잡는 한 줄',
  'sample_body': '스치듯 지나가지 않도록.',
  'description': '모야모야의 몽글한 포인트와 나눔스퀘어의 깔끔함.'},
 {'id': 70,
  'theme': '포인트 서체 조합',
  'title_font_name': 'HS활공명조',
  'body_font_name': '수트',
  'sample_title': '임팩트가 필요한 순간',
  'sample_body': '평범함 대신 개성을 선택하세요.',
  'description': '활공명조의 독특한 세리프 포인트와 수트의 모던 고딕 대비.'},
 {'id': 71,
  'theme': '포인트 서체 조합',
  'title_font_name': '웃맨체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '작은 디테일의 차이',
  'sample_body': '폰트 하나가 브랜드를 완성합니다.',
  'description': '웃맨체의 위트 있는 포인트와 노토산스의 안정감.'},
 {'id': 72,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Anton',
  'body_font_name': '프리텐다드',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Anton의 압축된 임팩트 + 프리텐다드 한글 본문. 세일 배너의 정석.'},
 {'id': 73,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Playfair Display',
  'body_font_name': '나눔명조',
  'sample_title': 'NEW ARRIVAL',
  'sample_body': '이번 주 새로 들어온 신상품을 만나보세요.',
  'description': 'Playfair의 클래식한 세리프와 나눔명조 — 매거진, 웨딩, 고급 무드.'},
 {'id': 74,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'DancingScript',
  'body_font_name': '마루부리',
  'sample_title': 'GRAND OPEN',
  'sample_body': '오픈 기념 전 상품 20% 할인 이벤트 진행 중.',
  'description': 'Dancing Script의 흐르는 필기체와 마루부리의 감성 본문.'},
 {'id': 75,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'BANGERS',
  'body_font_name': '나눔스퀘어',
  'sample_title': 'LIMITED EDITION',
  'sample_body': '한정 수량, 품절되면 재입고 어렵습니다.',
  'description': 'Bangers의 코믹한 임팩트와 나눔스퀘어의 깔끔한 한글 본문.'},
 {'id': 76,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Monoton',
  'body_font_name': '수트',
  'sample_title': 'WELCOME TO OUR STORE',
  'sample_body': '처음 오신 분들을 위한 특별 혜택을 준비했어요.',
  'description': 'Monoton의 네온사인 감성과 수트의 모던함 — 이벤트 배너용.'},
 {'id': 77,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Bungee',
  'body_font_name': '프리텐다드',
  'sample_title': 'BEST SELLER',
  'sample_body': '가장 많이 찾으신 인기 상품 모음.',
  'description': 'Bungee의 입체적인 임팩트와 프리텐다드의 균형.'},
 {'id': 78,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Lobster',
  'body_font_name': '고운바탕',
  'sample_title': 'SPECIAL OFFER',
  'sample_body': '이번 달에만 만나볼 수 있는 특가.',
  'description': 'Lobster의 부드러운 필기체와 고운바탕의 잔잔한 한글.'},
 {'id': 79,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'CinzelDecorative',
  'body_font_name': '나눔명조',
  'sample_title': 'THANK YOU',
  'sample_body': '늘 함께해주셔서 감사합니다.',
  'description': 'Cinzel의 고전적인 세리프와 나눔명조의 격조.'},
 {'id': 80,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'PressStart2P',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': 'COMING SOON',
  'sample_body': '곧 만나요, 기대해주세요.',
  'description': 'Press Start 2P의 픽셀 감성과 노토산스 — 게임 콘텐츠용.'},
 {'id': 81,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'KaushanScript',
  'body_font_name': '마루부리',
  'sample_title': 'HAPPY HOLIDAYS',
  'sample_body': '따뜻한 연말 보내시길 바랍니다.',
  'description': 'Kaushan Script의 유려한 흐름과 마루부리의 온기.'},
 {'id': 82,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '마포꽃섬',
  'body_font_name': '아리따 부리',
  'sample_title': '두 사람, 하나의 시작',
  'sample_body': '2026년 10월 24일 토요일 오후 2시, 그레이스홀에서 소중한 시간을 함께해 주세요.',
  'description': '마포꽃섬의 우아한 명조 제목과 아리따 부리의 격조 있는 본문 — 청첩장 정석 조합.'},
 {'id': 83,
  'theme': '웨딩 · 청첩장',
  'title_font_name': 'Playfair Display',
  'body_font_name': '나눔명조',
  'sample_title': 'SAVE THE DATE',
  'sample_body': '저희 두 사람이 사랑의 결실을 맺는 자리에 귀한 걸음 부탁드립니다.',
  'description': 'Playfair의 클래식 세리프와 나눔명조의 단정함 — 한영 혼용 청첩장에 잘 맞습니다.'},
 {'id': 84,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '상상토끼 꽃길',
  'body_font_name': '조선일보명조체',
  'sample_title': '오래도록 함께 걷겠습니다',
  'sample_body': '서로를 향한 믿음으로 새 가정을 이룹니다. 축복해 주세요.',
  'description': '꽃길체의 붓글씨 캘리그라피와 조선일보명조체의 고전적인 본문.'},
 {'id': 85,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '갬성명조',
  'body_font_name': '고운바탕',
  'sample_title': '봄날, 우리의 시작',
  'sample_body': '벚꽃이 흩날리던 그날처럼, 늘 설레는 마음으로 살겠습니다.',
  'description': '갬성명조의 손글씨 감성과 고운바탕의 담백한 안내 문구.'},
 {'id': 86,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '카페24 클랙식타입',
  'body_font_name': '을유1945',
  'sample_title': '두 가문의 만남',
  'sample_body': '자녀들의 결혼을 알려드립니다. 오셔서 축복해 주시면 감사하겠습니다.',
  'description': '클랙식타입의 빈티지 제목과 을유1945의 격식 있는 청첩 문구.'},
 {'id': 87,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '아리따 돋움',
  'body_font_name': '아리따 부리',
  'sample_title': 'OUR WEDDING DAY',
  'sample_body': '평생을 함께할 반려자를 만나 새로운 여정을 시작합니다.',
  'description': '아리따 돋움 제목과 아리따 부리 본문 — 같은 패밀리로 통일감 있는 청첩장.'},
 {'id': 88,
  'theme': '웨딩 · 청첩장',
  'title_font_name': '정묵바위체',
  'body_font_name': '나눔명조',
  'sample_title': '인연이 되어',
  'sample_body': '작은 인연이 큰 사랑이 되었습니다. 그 시작을 함께해 주세요.',
  'description': '정묵바위체의 묵직한 붓글씨와 나눔명조의 진중한 본문.'},
 {'id': 89,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': 'SB어그로체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '단 3일간의 폭탄 세일',
  'sample_body': '전 상품 최대 70% 할인, 이번 기회 놓치지 마세요.',
  'description': '어그로체의 강렬한 임팩트와 나눔스퀘어의 정보 전달력 — 세일 배너 필수 조합.'},
 {'id': 90,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '비트로코어',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '오늘 하루만 반값',
  'sample_body': '자정까지만 진행되는 깜짝 타임세일입니다.',
  'description': '비트로코어의 굵은 인상과 노토산스의 무난한 본문.'},
 {'id': 91,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '사천우주체',
  'body_font_name': '프리텐다드',
  'sample_title': 'FLASH SALE',
  'sample_body': '수량 한정, 선착순 마감됩니다.',
  'description': '사천우주체의 강렬한 제목과 프리텐다드의 세련된 부제.'},
 {'id': 92,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '망고보드 또박체',
  'body_font_name': '수트',
  'sample_title': '지금 가입하면 첫 달 무료',
  'sample_body': '신규 회원 한정 혜택, 지금 바로 신청하세요.',
  'description': '또박체의 또렷한 정보 전달력과 수트의 모던한 CTA 문구.'},
 {'id': 93,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '더잠실체',
  'body_font_name': '고운돋움',
  'sample_title': '창립 기념 감사 이벤트',
  'sample_body': '10주년을 맞아 준비한 특별한 혜택을 확인하세요.',
  'description': '더잠실체의 신뢰감 있는 제목과 고운돋움의 부드러운 본문.'},
 {'id': 94,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '넥슨 배찌체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '오늘만 이 가격',
  'sample_body': '깜짝 특가, 내일이면 사라집니다.',
  'description': '배찌체의 장난스러운 임팩트와 노토산스의 정보 전달력 대비.'},
 {'id': 95,
  'theme': '이벤트 · 프로모션 배너',
  'title_font_name': '열정도체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '마감 임박 D-1',
  'sample_body': '서두르세요, 내일이면 원래 가격으로 돌아갑니다.',
  'description': '열정도체의 뜨거운 인상과 나눔스퀘어의 안내 문구 조합.'},
 {'id': 96,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '배달의민족 도현체',
  'body_font_name': '프리텐다드',
  'sample_title': 'STUDIO DOHYUN',
  'sample_body': '브랜드 아이덴티티 디자인 스튜디오',
  'description': '도현체의 임팩트 있는 워드마크와 프리텐다드의 담백한 서브 정보.'},
 {'id': 97,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '아리따 돋움',
  'body_font_name': '고운돋움',
  'sample_title': '아리따 컨설팅',
  'sample_body': '경영 전략 · 브랜드 컨설팅',
  'description': '아리따 돋움의 신뢰감 있는 로고 타입과 고운돋움의 정보성 서브텍스트.'},
 {'id': 98,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '더잠실체',
  'body_font_name': '수트',
  'sample_title': '더잠실 어소시에이츠',
  'sample_body': '법률 · 세무 자문',
  'description': '더잠실체의 안정적인 인상이 전문직 명함에 신뢰를 더합니다.'},
 {'id': 99,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '원스토어 모바일고딕 제목체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': 'STORE LAB',
  'sample_body': 'UX/UI 디자인 에이전시',
  'description': '또렷한 로고체와 노토산스의 깔끔한 연락처 정보.'},
 {'id': 100,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '상상토끼 꽃길',
  'body_font_name': '갬성명조',
  'sample_title': '꽃길 플로리스트',
  'sample_body': '웨딩 · 이벤트 플라워',
  'description': '꽃길체의 손글씨 로고와 갬성명조의 감성적인 소개 문구.'},
 {'id': 101,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '정묵바위체',
  'body_font_name': '고운바탕',
  'sample_title': '먹, 담다',
  'sample_body': '전통 서예 공방',
  'description': '정묵바위체의 붓글씨 로고와 고운바탕의 차분한 본문 — 전통 브랜드에 적합.'},
 {'id': 102,
  'theme': '명함 · 브랜드 로고',
  'title_font_name': '잉크립퀴드',
  'body_font_name': '마루부리',
  'sample_title': 'INK & CO.',
  'sample_body': '뷰티 브랜드 컨설팅',
  'description': '잉크립퀴드의 강한 붓 획 로고와 마루부리의 우아한 서브텍스트.'},
 {'id': 103,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': 'IM혜민체',
  'body_font_name': '수트',
  'sample_title': '이거 실화냐고요',
  'sample_body': '진짜 있었던 일입니다, 끝까지 봐주세요.',
  'description': 'IM혜민체의 부드러운 자막과 수트의 깔끔한 정보 자막.'},
 {'id': 104,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': 'tvN 즐거운 이야기',
  'body_font_name': '고운돋움',
  'sample_title': '3초 만에 정리',
  'sample_body': '핵심만 빠르게 알려드릴게요.',
  'description': 'tvN 즐거운 이야기체의 친근한 느낌과 고운돋움의 서브 자막.'},
 {'id': 105,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '메모먼트 꾹꾹체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '저장 필수',
  'sample_body': '나중에 꼭 다시 보세요.',
  'description': '꾹꾹체의 또박또박한 강조 자막과 노토산스의 정보 전달.'},
 {'id': 106,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '다이어리체',
  'body_font_name': '프리텐다드',
  'sample_title': '오늘의 소소한 행복',
  'sample_body': '별거 아니지만 기록하고 싶었어요.',
  'description': '다이어리체의 아기자기함과 프리텐다드의 균형 잡힌 자막.'},
 {'id': 107,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '온글잎 콘콘체',
  'body_font_name': '수트',
  'sample_title': '팔로우하면 매일 떠요',
  'sample_body': '더 많은 콘텐츠는 프로필 링크에서.',
  'description': '콘콘체의 귀여운 손글씨와 수트의 CTA 자막.'},
 {'id': 108,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '교보손글씨 이유빈체',
  'body_font_name': '고운돋움',
  'sample_title': '댓글로 투표해주세요',
  'sample_body': 'A와 B, 여러분의 선택은?',
  'description': '이유빈체의 다정한 손글씨와 고운돋움의 참여 유도 자막.'},
 {'id': 109,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '이서윤체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '풀버전은 유튜브에',
  'sample_body': '짧게 못 담은 이야기가 더 있어요.',
  'description': '이서윤체의 단정한 손글씨와 노토산스의 안내 자막.'},
 {'id': 110,
  'theme': '인스타 릴스 · 숏폼 자막',
  'title_font_name': '잉크립퀴드',
  'body_font_name': '프리텐다드',
  'sample_title': '이 노래 제목 아시는 분',
  'sample_body': '댓글로 알려주시면 감사하겠습니다.',
  'description': '잉크립퀴드의 감성적인 자막과 프리텐다드의 정보 자막 대비.'},
 {'id': 111,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': 'KoPub바탕',
  'body_font_name': '나눔명조',
  'sample_title': '천천히 읽는 하루',
  'sample_body': '빠르게 흘러가는 일상 속에서, 문장 하나에 잠시 머물러 봅니다. 오늘은 그런 이야기를 나눠볼까 합니다.',
  'description': 'KoPub바탕과 나눔명조 둘 다 장문 가독성이 뛰어나 긴 글에 적합합니다.'},
 {'id': 112,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '을유1945',
  'body_font_name': '아리따 부리',
  'sample_title': '계절이 바뀌는 소리',
  'sample_body': '창밖 나뭇잎 색이 조금씩 달라지고 있습니다. 올해도 어김없이 가을이 찾아왔습니다.',
  'description': '을유1945의 고전적인 제목과 아리따 부리의 우아한 본문 — 에세이류에 잘 맞습니다.'},
 {'id': 113,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '마루부리',
  'body_font_name': '조선일보명조체',
  'sample_title': '다시 꺼내 읽는 책',
  'sample_body': '몇 년 전 읽었던 책을 다시 펼쳤습니다. 그때와 지금, 같은 문장이 다르게 다가옵니다.',
  'description': '마루부리의 부드러운 제목과 조선일보명조체의 신뢰감 있는 본문.'},
 {'id': 114,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '제주명조',
  'body_font_name': '나눔명조',
  'sample_title': '여행에서 돌아와',
  'sample_body': '낯선 곳에서의 며칠이 일상을 새롭게 보게 해주었습니다. 여행의 기록을 남깁니다.',
  'description': '제주명조와 나눔명조의 조합, 잔잔하고 담백한 여행기에 어울립니다.'},
 {'id': 115,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '조선일보명조체',
  'body_font_name': 'KoPub바탕',
  'sample_title': '오래된 편지를 정리하며',
  'sample_body': '서랍 속 편지 뭉치를 발견했습니다. 그 시절의 마음이 고스란히 담겨 있었습니다.',
  'description': '조선일보명조체의 격식과 KoPub바탕의 안정적인 가독성.'},
 {'id': 116,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '아리따 부리',
  'body_font_name': '마루부리',
  'sample_title': '한 잔의 여유',
  'sample_body': '바쁜 하루 중 잠시, 차 한 잔을 마시며 생각을 정리하는 시간을 가져봅니다.',
  'description': '아리따 부리와 마루부리 모두 명조 계열로 잔잔한 무드의 매거진 본문에 적합.'},
 {'id': 117,
  'theme': '블로그 · 매거진 본문',
  'title_font_name': '나눔명조',
  'body_font_name': '을유1945',
  'sample_title': '기록이 남긴 것들',
  'sample_body': '매일 쓴 짧은 메모들이 모여 한 해를 돌아보게 합니다.',
  'description': '나눔명조의 단정한 제목과 을유1945의 고전적인 본문.'},
 {'id': 118,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '넥슨 배찌체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '오늘의 숫자 놀이',
  'sample_body': '함께 세어볼까요? 하나, 둘, 셋!',
  'description': '배찌체의 장난스러운 제목과 나눔스퀘어의 또렷한 설명 문구.'},
 {'id': 119,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '메이플스토리',
  'body_font_name': '고운돋움',
  'sample_title': '우리 반 이야기 시간',
  'sample_body': '오늘은 어떤 이야기가 기다리고 있을까요?',
  'description': '메이플스토리체의 친근함과 고운돋움의 부드러운 안내문.'},
 {'id': 120,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '수박양체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '알림장 - 준비물 안내',
  'sample_body': '내일은 색종이와 가위를 가져와 주세요.',
  'description': '수박양체의 귀여운 제목과 나눔스퀘어의 명확한 정보 전달.'},
 {'id': 121,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '온글잎 박다현체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '이번 주 그림일기',
  'sample_body': '가장 기억에 남는 순간을 그려보아요.',
  'description': '박다현체의 친근한 손글씨와 노토산스의 안정적인 설명.'},
 {'id': 122,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '온글잎 밑미',
  'body_font_name': '고운바탕',
  'sample_title': '동화 속으로 떠나요',
  'sample_body': '오늘 함께 읽을 이야기는 무엇일까요?',
  'description': '밑미체의 다정한 손글씨와 고운바탕의 차분한 본문.'},
 {'id': 123,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '강원교육모두',
  'body_font_name': '나눔스퀘어',
  'sample_title': '학예회 안내',
  'sample_body': '이번 달 마지막 주 금요일, 강당에서 만나요.',
  'description': '강원교육모두의 반듯한 손글씨와 나눔스퀘어의 안내 정보.'},
 {'id': 124,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': 'KCC간판체',
  'body_font_name': 'KoPub돋움',
  'sample_title': '안전 교육 시간',
  'sample_body': '횡단보도를 건널 땐 좌우를 꼭 살펴요.',
  'description': 'KCC간판체의 또박또박함과 KoPub돋움의 정보 전달력.'},
 {'id': 125,
  'theme': '키즈 · 교육 콘텐츠',
  'title_font_name': '원스토어 모바일POP체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘의 칭찬 스티커',
  'sample_body': '숙제를 스스로 해낸 친구들에게 드려요.',
  'description': 'POP체의 장난스러운 제목과 고운돋움의 부드러운 설명.'},
 {'id': 126,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '카카오큰글씨',
  'body_font_name': 'KoPub바탕',
  'sample_title': '2026년도 기초연금 안내',
  'sample_body': '신청 대상과 방법을 큰 글씨로 안내해 드립니다.',
  'description': '카카오큰글씨는 저시력자도 읽기 쉽도록 설계된 서체로 관공서 안내문에 최적.'},
 {'id': 127,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '나눔고딕',
  'body_font_name': '나눔명조',
  'sample_title': '무료 건강검진 안내',
  'sample_body': '가까운 보건소에서 신분증을 지참하고 방문해 주세요.',
  'description': '나눔고딕의 깔끔한 제목과 나눔명조의 안정적인 안내 본문.'},
 {'id': 128,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '경기천년제목',
  'body_font_name': '서울알림체',
  'sample_title': '노인 일자리 사업 모집',
  'sample_body': '만 65세 이상 어르신을 대상으로 접수를 시작합니다.',
  'description': '경기천년제목의 신뢰감 있는 제목과 서울알림체의 정확한 정보 전달.'},
 {'id': 129,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '서울알림체',
  'body_font_name': 'KoPub돋움',
  'sample_title': '민원 처리 절차 안내',
  'sample_body': '방문 전 아래 순서를 확인해 주시면 더욱 빠르게 처리됩니다.',
  'description': '서울알림체와 KoPub돋움 모두 공공기관 표준 서체로 신뢰도가 높습니다.'},
 {'id': 130,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '학교안심 둥근미소',
  'body_font_name': '나눔고딕',
  'sample_title': '경로당 프로그램 안내',
  'sample_body': '매주 화요일과 목요일, 건강 체조 교실을 운영합니다.',
  'description': '둥근미소의 친근한 제목과 나눔고딕의 명확한 본문.'},
 {'id': 131,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '강원교육모두',
  'body_font_name': 'KoPub바탕',
  'sample_title': '복지 혜택 안내문',
  'sample_body': '올해 새로 생긴 지원 제도를 꼼꼼히 확인해 보세요.',
  'description': '강원교육모두의 부드러운 제목과 KoPub바탕의 격식 있는 본문.'},
 {'id': 132,
  'theme': '시니어 친화 · 관공서',
  'title_font_name': '카카오큰글씨',
  'body_font_name': '나눔스퀘어',
  'sample_title': '전화 사기 예방 교육',
  'sample_body': '모르는 번호로 걸려온 송금 요청은 꼭 확인하세요.',
  'description': '큰 글씨로 시인성을 높이고 나눔스퀘어로 정보를 명확히 전달합니다.'},
 {'id': 133,
  'theme': '반려동물',
  'title_font_name': '넷마블체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘도 산책 가는 날',
  'sample_body': '우리 강아지가 제일 좋아하는 시간이에요.',
  'description': '넷마블체의 부드러운 제목과 고운돋움의 다정한 본문.'},
 {'id': 134,
  'theme': '반려동물',
  'title_font_name': '산돌 삼립호빵체 Basic',
  'body_font_name': '나눔스퀘어',
  'sample_title': '첫 목욕은 조심조심',
  'sample_body': '처음 목욕시키는 보호자를 위한 안내입니다.',
  'description': '호빵체의 폭신한 느낌과 나눔스퀘어의 명확한 정보 전달.'},
 {'id': 135,
  'theme': '반려동물',
  'title_font_name': '머니그라피 라운디드',
  'body_font_name': '수트',
  'sample_title': '펫샵 오픈 안내',
  'sample_body': '우리 동네에 작은 펫샵이 생겼어요.',
  'description': '라운디드체의 부드러운 로고감과 수트의 모던한 안내 문구.'},
 {'id': 136,
  'theme': '반려동물',
  'title_font_name': '아이크리수진체',
  'body_font_name': '고운돋움',
  'sample_title': '냥이의 하루',
  'sample_body': '자고, 놀고, 또 자고 — 오늘도 평화로운 하루.',
  'description': '아이크리수진체의 친근한 손글씨와 고운돋움의 담백한 본문.'},
 {'id': 137,
  'theme': '반려동물',
  'title_font_name': '조선굴림체',
  'body_font_name': '나눔고딕',
  'sample_title': '반려동물 등록 안내',
  'sample_body': '동물병원에서 간편하게 등록하실 수 있습니다.',
  'description': '조선굴림체의 부드러운 제목과 나눔고딕의 정보 전달력.'},
 {'id': 138,
  'theme': '반려동물',
  'title_font_name': '레코체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '강아지 사료 고르는 법',
  'sample_body': '연령과 체중에 맞는 사료 선택 가이드.',
  'description': '레코체의 깔끔한 제목과 노토산스의 정보성 본문.'},
 {'id': 139,
  'theme': '반려동물',
  'title_font_name': '스포카 한 산스',
  'body_font_name': '고운돋움',
  'sample_title': '동물병원 예방접종 안내',
  'sample_body': '시기별 필수 접종 일정을 확인하세요.',
  'description': '스포카 한 산스의 신뢰감 있는 제목과 고운돋움의 부드러운 설명.'}]
