"""폰트 페어링 시드 데이터 v3 (81조합 · 8테마)

- PAIRING_SEED_VERSION이 바뀌면 seed.py가 기존 시드를 지우고 재삽입
- 이름 기준으로 DB 폰트와 매칭, 없는 폰트 조합은 자동 스킵
- 어드민 페어링 관리(2단계) 도입 후에는 버전을 올리지 말 것 (수동 데이터 보호)
"""

PAIRING_SEED_VERSION = "3"

PAIRING_SEED = [{'id': 1,
  'theme': '유튜브 썸네일',
  'title_font_name': '검은고딕',
  'body_font_name': '프리텐다드',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '가장 두꺼운 검은고딕이 시선을 잡고, 프리텐다드가 부제를 담백하게 받쳐줍니다.'},
 {'id': 2,
  'theme': '유튜브 썸네일',
  'title_font_name': 'SB어그로체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '어그로체 특유의 임팩트에 나눔스퀘어의 단정함이 균형을 만듭니다.'},
 {'id': 3,
  'theme': '유튜브 썸네일',
  'title_font_name': '티몬 몬소리체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '몬소리체의 개성 있는 두께감과 노토산스의 무난한 가독성 조합.'},
 {'id': 4,
  'theme': '유튜브 썸네일',
  'title_font_name': '서울로',
  'body_font_name': '수트',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '서울로의 꽉 찬 임팩트와 수트의 모던한 부제 — 도시적인 썸네일 조합.'},
 {'id': 5,
  'theme': '유튜브 썸네일',
  'title_font_name': '경기천년제목',
  'body_font_name': '서울알림체',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '경기천년제목의 묵직한 존재감을 서울알림체가 깔끔하게 받쳐줍니다.'},
 {'id': 6,
  'theme': '유튜브 썸네일',
  'title_font_name': '열정도체',
  'body_font_name': '프리텐다드',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '열정도체의 뜨거운 획과 프리텐다드의 차분한 부제 — 강렬한 대비.'},
 {'id': 7,
  'theme': '유튜브 썸네일',
  'title_font_name': '이누아리두리네',
  'body_font_name': '수트',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '이누아리두리네의 압도적인 두께를 수트가 깔끔하게 정리합니다.'},
 {'id': 8,
  'theme': '유튜브 썸네일',
  'title_font_name': '이사만루체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '이사만루체의 스포츠 임팩트와 노토산스의 안정감.'},
 {'id': 9,
  'theme': '유튜브 썸네일',
  'title_font_name': '원스토어 모바일고딕 제목체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '원스토어 제목체의 또렷한 획과 나눔스퀘어의 단정한 부제.'},
 {'id': 10,
  'theme': '유튜브 썸네일',
  'title_font_name': '와일드각',
  'body_font_name': '프리텐다드',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '와일드각의 날카로운 개성에 프리텐다드의 균형감.'},
 {'id': 11,
  'theme': '유튜브 썸네일',
  'title_font_name': '던파 비트비트체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '비트비트체의 게임 감성과 노토산스의 무난함 — 게임·리뷰 채널용.'},
 {'id': 12,
  'theme': '유튜브 썸네일',
  'title_font_name': '세방고딕',
  'body_font_name': '수트',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '세방고딕의 클래식한 굵기와 수트의 현대적인 부제.'},
 {'id': 13,
  'theme': '유튜브 썸네일',
  'title_font_name': '태나다체',
  'body_font_name': '프리텐다드',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '태나다체의 독특한 존재감을 프리텐다드가 받쳐줍니다.'},
 {'id': 14,
  'theme': '유튜브 썸네일',
  'title_font_name': 'HS산토끼체',
  'body_font_name': '고운돋움',
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '산토끼체의 통통 튀는 매력과 고운돋움의 부드러움.'},
 {'id': 15,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '여기어때 잘난체',
  'body_font_name': 'KoPub돋움',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '잘난체의 친근한 볼륨감과 KoPub돋움의 안정적인 본문 가독성.'},
 {'id': 16,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '에스코어드림',
  'body_font_name': '나눔스퀘어',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '에스코어드림 굵은 웨이트로 제목, 나눔스퀘어로 본문 — 정보성 카드뉴스의 정석.'},
 {'id': 17,
  'theme': '카드뉴스 · SNS',
  'title_font_name': 'G마켓 산스',
  'body_font_name': '프리텐다드',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': 'G마켓 산스와 프리텐다드, 둘 다 화면용으로 설계돼 어떤 주제든 무난합니다.'},
 {'id': 18,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '푸른숲체',
  'body_font_name': '수트',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '푸른숲체의 자연스러운 제목과 수트의 정돈된 본문 — 공익·환경 콘텐츠에 잘 맞습니다.'},
 {'id': 19,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '리아체',
  'body_font_name': '고운돋움',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '리아체의 통통 튀는 임팩트를 고운돋움이 부드럽게 중화해 줍니다.'},
 {'id': 20,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '창원단감아삭체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '단감아삭체의 아삭한 개성과 노토산스의 정돈된 본문.'},
 {'id': 21,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '평창평화체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '평화체의 부드러운 곡선과 나눔스퀘어의 단정함.'},
 {'id': 22,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '하남다움체',
  'body_font_name': '수트',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '하남다움체의 도시적인 제목과 수트의 모던한 본문.'},
 {'id': 23,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '카페24 아네모네',
  'body_font_name': '고운돋움',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '아네모네의 감성적인 곡선과 고운돋움의 차분한 본문.'},
 {'id': 24,
  'theme': '카드뉴스 · SNS',
  'title_font_name': 'Y너만을 비춤체',
  'body_font_name': '프리텐다드',
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '비춤체의 반짝이는 개성과 프리텐다드의 안정감.'},
 {'id': 25,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '배달의민족 주아체',
  'body_font_name': '마루부리',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '주아체의 붓 터치 느낌과 마루부리의 부드러운 명조가 손맛을 살립니다.'},
 {'id': 26,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '카페24 써라운드',
  'body_font_name': '아리따 부리',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '써라운드의 둥근 제목과 아리따 부리의 우아한 본문 — 브랜드 무드에 적합.'},
 {'id': 27,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '티머니 둥근바람',
  'body_font_name': '고운바탕',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '둥근바람의 몽글몽글한 제목과 고운바탕의 잔잔한 명조 본문.'},
 {'id': 28,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '낭만있구미체',
  'body_font_name': '갬성명조',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '낭만있구미체의 레트로 굴림과 갬성명조의 손글씨 감성 — 이름 그대로 낭만 조합.'},
 {'id': 29,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '땅스부대찌개',
  'body_font_name': '제주명조',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '부대찌개체의 통통한 개성과 제주명조의 차분함이 대비를 만듭니다.'},
 {'id': 30,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '카페24 클랙식타입',
  'body_font_name': '나눔명조',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '클랙식타입의 빈티지한 획과 나눔명조의 클래식함 — 레트로 브랜딩.'},
 {'id': 31,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': 'HS산토끼체',
  'body_font_name': '고운바탕',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '산토끼체의 귀여운 제목과 고운바탕의 담백한 본문.'},
 {'id': 32,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '빙그레싸만코체',
  'body_font_name': '마루부리',
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '싸만코체의 말랑한 제목과 마루부리의 온화한 본문.'},
 {'id': 33,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 을지로체',
  'body_font_name': '나눔명조',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '을지로체의 레트로 간판 감성과 나눔명조의 신뢰감 있는 본문.'},
 {'id': 34,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 한나체',
  'body_font_name': 'KoPub바탕',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '한나체의 투박한 매력을 KoPub바탕이 차분하게 정리해줍니다.'},
 {'id': 35,
  'theme': '포스터 · 안내문',
  'title_font_name': 'MBC1961',
  'body_font_name': '을유1945',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': 'MBC1961의 옛 방송 자막 느낌과 을유1945 — 레트로 무드 완성 조합.'},
 {'id': 36,
  'theme': '포스터 · 안내문',
  'title_font_name': '워헤이븐',
  'body_font_name': '수트',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '워헤이븐의 독특한 세리프 제목과 수트의 모던 고딕 — 대비가 만드는 긴장감.'},
 {'id': 37,
  'theme': '포스터 · 안내문',
  'title_font_name': '웃맨체',
  'body_font_name': '고운바탕',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '웃맨체의 개성 있는 획과 고운바탕의 단정함, 전시·행사 포스터용.'},
 {'id': 38,
  'theme': '포스터 · 안내문',
  'title_font_name': '을지로 10년후 체',
  'body_font_name': '나눔명조',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '을지로 10년후 체의 바랜 감성과 나눔명조의 진중함 — 전시 포스터에 좋습니다.'},
 {'id': 39,
  'theme': '포스터 · 안내문',
  'title_font_name': '케리스 케듀체',
  'body_font_name': '서울알림체',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '케듀체의 또렷한 제목과 서울알림체의 정보 전달력 — 교육 안내문용.'},
 {'id': 40,
  'theme': '포스터 · 안내문',
  'title_font_name': '학교안심 둥근미소',
  'body_font_name': 'KoPub돋움',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '둥근미소의 친근한 제목과 KoPub돋움의 안정적인 본문 — 학교·기관 안내문.'},
 {'id': 41,
  'theme': '포스터 · 안내문',
  'title_font_name': '강원교육모두',
  'body_font_name': '나눔스퀘어',
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '강원교육모두의 반듯한 손글씨와 나눔스퀘어의 정돈된 본문.'},
 {'id': 42,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '상상토끼 꽃길',
  'body_font_name': '부크크 명조',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '꽃길체의 붓글씨 제목에 부크크 명조의 잔잔한 본문이 어울립니다.'},
 {'id': 43,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '잉크립퀴드',
  'body_font_name': '마루부리',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '잉크립퀴드의 강한 붓 획과 마루부리의 온화함 — 강약 대비가 좋습니다.'},
 {'id': 44,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '쿨가이체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '쿨가이체의 시원한 캘리 획을 고운돋움이 차분하게 받쳐줍니다.'},
 {'id': 45,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '정묵바위체',
  'body_font_name': '을유1945',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '정묵바위체의 묵직한 붓글씨와 을유1945의 고전미.'},
 {'id': 46,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '그리운 경찰감성체',
  'body_font_name': '고운바탕',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '경찰감성체의 그리운 손글씨와 고운바탕의 담백함.'},
 {'id': 47,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '정선아리랑체',
  'body_font_name': '나눔명조',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '정선아리랑체의 유려한 획과 나눔명조의 단정함.'},
 {'id': 48,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '완도희망체',
  'body_font_name': '마루부리',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '완도희망체의 힘 있는 붓글씨와 마루부리의 부드러움.'},
 {'id': 49,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '신비는 일곱살',
  'body_font_name': '나눔스퀘어',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '신비는 일곱살의 아이 손글씨와 나눔스퀘어의 깔끔함.'},
 {'id': 50,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '이서윤체',
  'body_font_name': '프리텐다드',
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '이서윤체의 단정한 손글씨와 프리텐다드의 현대적인 본문.'},
 {'id': 51,
  'theme': '브이로그 자막',
  'title_font_name': '귀욤뭉이',
  'body_font_name': '수트',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '귀욤뭉이의 몽글한 손글씨 자막과 수트의 깔끔한 정보 자막 조합.'},
 {'id': 52,
  'theme': '브이로그 자막',
  'title_font_name': '빙그레체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '빙그레체의 명랑한 제목 자막과 고운돋움의 잔잔한 서브 자막.'},
 {'id': 53,
  'theme': '브이로그 자막',
  'title_font_name': '사진관',
  'body_font_name': '서울알림체',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '사진관체의 손글씨 감성과 서울알림체의 또렷한 정보 전달력.'},
 {'id': 54,
  'theme': '브이로그 자막',
  'title_font_name': '온글잎 콘콘체',
  'body_font_name': '나눔스퀘어',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '콘콘체의 귀여운 손글씨와 나눔스퀘어의 깔끔함 — 다이어리 무드.'},
 {'id': 55,
  'theme': '브이로그 자막',
  'title_font_name': '바른생활',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '바른생활체의 또박또박한 자막과 노토산스의 안정감.'},
 {'id': 56,
  'theme': '브이로그 자막',
  'title_font_name': '갬성명조',
  'body_font_name': '수트',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '갬성명조의 감성 자막과 수트의 담백한 정보 자막.'},
 {'id': 57,
  'theme': '브이로그 자막',
  'title_font_name': '다이어리체',
  'body_font_name': '프리텐다드',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '다이어리체의 아기자기함과 프리텐다드의 깔끔함.'},
 {'id': 58,
  'theme': '브이로그 자막',
  'title_font_name': '오뮤 다예쁨체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '다예쁨체의 예쁜 손글씨와 고운돋움의 차분함.'},
 {'id': 59,
  'theme': '브이로그 자막',
  'title_font_name': '온글잎 긍정',
  'body_font_name': '나눔스퀘어',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '온글잎 긍정의 밝은 손글씨와 나눔스퀘어의 정돈됨.'},
 {'id': 60,
  'theme': '브이로그 자막',
  'title_font_name': '교보손글씨 2019',
  'body_font_name': '수트',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '교보손글씨의 따뜻함과 수트의 모던한 정보 자막.'},
 {'id': 61,
  'theme': '브이로그 자막',
  'title_font_name': '교보손글씨 이유빈체',
  'body_font_name': '고운돋움',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '이유빈체의 귀여운 손글씨와 고운돋움의 부드러움.'},
 {'id': 62,
  'theme': '브이로그 자막',
  'title_font_name': '둘기마요고딕',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '둘기마요고딕의 동글동글함과 노토산스의 무난함.'},
 {'id': 63,
  'theme': '브이로그 자막',
  'title_font_name': '카페 24 쑥쑥',
  'body_font_name': '서울알림체',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '쑥쑥체의 아이 같은 손글씨와 서울알림체의 또렷함.'},
 {'id': 64,
  'theme': '브이로그 자막',
  'title_font_name': '학교안심 받아쓰기',
  'body_font_name': 'KoPub돋움',
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '받아쓰기체의 또박또박함과 KoPub돋움의 안정적인 자막.'},
 {'id': 65,
  'theme': '포인트 서체 조합',
  'title_font_name': 'Y최애체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '최애체의 개성 있는 포인트와 노토산스의 담백한 본문.'},
 {'id': 66,
  'theme': '포인트 서체 조합',
  'title_font_name': 'Y클로버체',
  'body_font_name': '수트',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '클로버체의 러블리한 포인트와 수트의 모던함.'},
 {'id': 67,
  'theme': '포인트 서체 조합',
  'title_font_name': '배달의민족 꾸불림체',
  'body_font_name': '프리텐다드',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '꾸불림체의 유쾌한 곡선과 프리텐다드의 균형감.'},
 {'id': 68,
  'theme': '포인트 서체 조합',
  'title_font_name': '빛의계승자체',
  'body_font_name': 'KoPub바탕',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '빛의계승자체의 판타지 감성과 KoPub바탕의 진중함.'},
 {'id': 69,
  'theme': '포인트 서체 조합',
  'title_font_name': '카페24 모야모야',
  'body_font_name': '나눔스퀘어',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '모야모야의 몽글한 포인트와 나눔스퀘어의 깔끔함.'},
 {'id': 70,
  'theme': '포인트 서체 조합',
  'title_font_name': 'HS활공명조',
  'body_font_name': '수트',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '활공명조의 독특한 세리프 포인트와 수트의 모던 고딕 대비.'},
 {'id': 71,
  'theme': '포인트 서체 조합',
  'title_font_name': '웃맨체',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': '조금 특별한 하루',
  'sample_body': '평범한 문장도 서체 하나로 분위기가 달라집니다.',
  'description': '웃맨체의 위트 있는 포인트와 노토산스의 안정감.'},
 {'id': 72,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Anton',
  'body_font_name': '프리텐다드',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Anton의 압축된 임팩트 + 프리텐다드 한글 본문. 세일 배너의 정석.'},
 {'id': 73,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Playfair Display',
  'body_font_name': '나눔명조',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Playfair의 클래식한 세리프와 나눔명조 — 매거진, 웨딩, 고급 무드.'},
 {'id': 74,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'DancingScript',
  'body_font_name': '마루부리',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Dancing Script의 흐르는 필기체와 마루부리의 감성 본문.'},
 {'id': 75,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'BANGERS',
  'body_font_name': '나눔스퀘어',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Bangers의 코믹한 임팩트와 나눔스퀘어의 깔끔한 한글 본문.'},
 {'id': 76,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Monoton',
  'body_font_name': '수트',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Monoton의 네온사인 감성과 수트의 모던함 — 이벤트 배너용.'},
 {'id': 77,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Bungee',
  'body_font_name': '프리텐다드',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Bungee의 입체적인 임팩트와 프리텐다드의 균형.'},
 {'id': 78,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Lobster',
  'body_font_name': '고운바탕',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Lobster의 부드러운 필기체와 고운바탕의 잔잔한 한글.'},
 {'id': 79,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'CinzelDecorative',
  'body_font_name': '나눔명조',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Cinzel의 고전적인 세리프와 나눔명조의 격조.'},
 {'id': 80,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'PressStart2P',
  'body_font_name': 'Noto Sans CJK KR',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Press Start 2P의 픽셀 감성과 노토산스 — 게임 콘텐츠용.'},
 {'id': 81,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'KaushanScript',
  'body_font_name': '마루부리',
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Kaushan Script의 유려한 흐름과 마루부리의 온기.'}]
