"""폰트 페어링 시드 데이터 (30조합 · 7테마)

- 이름 기준으로 DB 폰트와 매칭됨 (seed._seed_pairings)
- DB에 없는 폰트가 포함된 조합은 자동으로 건너뜀
- 어드민 페어링 관리 기능(2단계) 도입 전까지의 초기 데이터
"""

PAIRING_SEED = [{'id': 1,
  'theme': '유튜브 썸네일',
  'title_font_name': '검은고딕',
  'title_font_seed_id': 17,
  'body_font_name': '프리텐다드',
  'body_font_seed_id': 101,
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '가장 두꺼운 검은고딕이 시선을 잡고, 프리텐다드가 부제를 담백하게 받쳐줍니다.'},
 {'id': 2,
  'theme': '유튜브 썸네일',
  'title_font_name': 'SB어그로체',
  'title_font_seed_id': 11,
  'body_font_name': '나눔스퀘어',
  'body_font_seed_id': 23,
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '어그로체 특유의 임팩트에 나눔스퀘어의 단정함이 균형을 만듭니다.'},
 {'id': 3,
  'theme': '유튜브 썸네일',
  'title_font_name': '티몬 몬소리체',
  'title_font_seed_id': 97,
  'body_font_name': 'Noto Sans CJK KR',
  'body_font_seed_id': 10,
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '몬소리체의 개성 있는 두께감과 노토산스의 무난한 가독성 조합.'},
 {'id': 4,
  'theme': '유튜브 썸네일',
  'title_font_name': '서울로',
  'title_font_seed_id': None,
  'body_font_name': '수트',
  'body_font_seed_id': None,
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '서울로의 꽉 찬 임팩트와 수트의 모던한 부제 — 도시적인 썸네일 조합.'},
 {'id': 5,
  'theme': '유튜브 썸네일',
  'title_font_name': '경기천년제목',
  'title_font_seed_id': None,
  'body_font_name': '서울알림체',
  'body_font_seed_id': None,
  'sample_title': '구독자 10만 돌파!',
  'sample_body': '지금 바로 확인해 보세요',
  'description': '경기천년제목의 묵직한 존재감을 서울알림체가 깔끔하게 받쳐줍니다.'},
 {'id': 6,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '여기어때 잘난체',
  'title_font_seed_id': 62,
  'body_font_name': 'KoPub돋움',
  'body_font_seed_id': 7,
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '잘난체의 친근한 볼륨감과 KoPub돋움의 안정적인 본문 가독성.'},
 {'id': 7,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '에스코어드림',
  'title_font_seed_id': 61,
  'body_font_name': '나눔스퀘어',
  'body_font_seed_id': 23,
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '에스코어드림 굵은 웨이트로 제목, 나눔스퀘어로 본문 — 정보성 카드뉴스의 정석.'},
 {'id': 8,
  'theme': '카드뉴스 · SNS',
  'title_font_name': 'G마켓 산스',
  'title_font_seed_id': 1,
  'body_font_name': '프리텐다드',
  'body_font_seed_id': 101,
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': 'G마켓 산스와 프리텐다드, 둘 다 화면용으로 설계돼 어떤 주제든 무난합니다.'},
 {'id': 9,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '푸른숲체',
  'title_font_seed_id': None,
  'body_font_name': '수트',
  'body_font_seed_id': None,
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '푸른숲체의 자연스러운 제목과 수트의 정돈된 본문 — 공익·환경 콘텐츠에 잘 맞습니다.'},
 {'id': 10,
  'theme': '카드뉴스 · SNS',
  'title_font_name': '리아체',
  'title_font_seed_id': None,
  'body_font_name': '고운돋움',
  'body_font_seed_id': None,
  'sample_title': '월급 관리 꿀팁 5가지',
  'sample_body': '사회초년생이라면 꼭 알아야 할 저축 습관을 정리했어요.',
  'description': '리아체의 통통 튀는 임팩트를 고운돋움이 부드럽게 중화해 줍니다.'},
 {'id': 11,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '배달의민족 주아체',
  'title_font_seed_id': 42,
  'body_font_name': '마루부리',
  'body_font_seed_id': 33,
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '주아체의 붓 터치 느낌과 마루부리의 부드러운 명조가 손맛을 살립니다.'},
 {'id': 12,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '카페24 써라운드',
  'title_font_seed_id': 92,
  'body_font_name': '아리따 부리',
  'body_font_seed_id': 59,
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '써라운드의 둥근 제목과 아리따 부리의 우아한 본문 — 브랜드 무드에 적합.'},
 {'id': 13,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '티머니 둥근바람',
  'title_font_seed_id': None,
  'body_font_name': '고운바탕',
  'body_font_seed_id': None,
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '둥근바람의 몽글몽글한 제목과 고운바탕의 잔잔한 명조 본문.'},
 {'id': 14,
  'theme': '감성 카페 · 브랜딩',
  'title_font_name': '낭만있구미체',
  'title_font_seed_id': None,
  'body_font_name': '갬성명조',
  'body_font_seed_id': None,
  'sample_title': '주말엔 동네 빵집',
  'sample_body': '갓 구운 소금빵과 드립 커피 한 잔의 여유.',
  'description': '낭만있구미체의 레트로 굴림과 갬성명조의 손글씨 감성 — 이름 그대로 낭만 조합.'},
 {'id': 15,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 을지로체',
  'title_font_seed_id': 41,
  'body_font_name': '나눔명조',
  'body_font_seed_id': 22,
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '을지로체의 레트로 간판 감성과 나눔명조의 신뢰감 있는 본문.'},
 {'id': 16,
  'theme': '포스터 · 안내문',
  'title_font_name': '배달의민족 한나체',
  'title_font_seed_id': 43,
  'body_font_name': 'KoPub바탕',
  'body_font_seed_id': 8,
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '한나체의 투박한 매력을 KoPub바탕이 차분하게 정리해줍니다.'},
 {'id': 17,
  'theme': '포스터 · 안내문',
  'title_font_name': 'MBC1961',
  'title_font_seed_id': 9,
  'body_font_name': '을유1945',
  'body_font_seed_id': 72,
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': 'MBC1961의 옛 방송 자막 느낌과 을유1945 — 레트로 무드 완성 조합.'},
 {'id': 18,
  'theme': '포스터 · 안내문',
  'title_font_name': '워헤이븐',
  'title_font_seed_id': None,
  'body_font_name': '수트',
  'body_font_seed_id': None,
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '워헤이븐의 독특한 세리프 제목과 수트의 모던 고딕 — 대비가 만드는 긴장감.'},
 {'id': 19,
  'theme': '포스터 · 안내문',
  'title_font_name': '웃맨체',
  'title_font_seed_id': None,
  'body_font_name': '고운바탕',
  'body_font_seed_id': None,
  'sample_title': '3월 독서 모임 안내',
  'sample_body': '매주 목요일 저녁 7시, 도서관 세미나실에서 만나요.',
  'description': '웃맨체의 개성 있는 획과 고운바탕의 단정함, 전시·행사 포스터용.'},
 {'id': 20,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '상상토끼 꽃길',
  'title_font_seed_id': 52,
  'body_font_name': '부크크 명조',
  'body_font_seed_id': 46,
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '꽃길체의 붓글씨 제목에 부크크 명조의 잔잔한 본문이 어울립니다.'},
 {'id': 21,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '잉크립퀴드',
  'title_font_seed_id': 78,
  'body_font_name': '마루부리',
  'body_font_seed_id': 33,
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '잉크립퀴드의 강한 붓 획과 마루부리의 온화함 — 강약 대비가 좋습니다.'},
 {'id': 22,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '쿨가이체',
  'title_font_seed_id': None,
  'body_font_name': '고운돋움',
  'body_font_seed_id': None,
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '쿨가이체의 시원한 캘리 획을 고운돋움이 차분하게 받쳐줍니다.'},
 {'id': 23,
  'theme': '캘리 · 손글씨 감성',
  'title_font_name': '날쌘돌이체',
  'title_font_seed_id': None,
  'body_font_name': '고운바탕',
  'body_font_seed_id': None,
  'sample_title': '오늘도 수고했어요',
  'sample_body': '당신의 하루가 조금 더 따뜻해지기를.',
  'description': '날쌘돌이체의 속도감 있는 붓글씨와 고운바탕의 명조 본문.'},
 {'id': 24,
  'theme': '브이로그 자막',
  'title_font_name': '귀욤뭉이',
  'title_font_seed_id': None,
  'body_font_name': '수트',
  'body_font_seed_id': None,
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '귀욤뭉이의 몽글한 손글씨 자막과 수트의 깔끔한 정보 자막 조합.'},
 {'id': 25,
  'theme': '브이로그 자막',
  'title_font_name': '빙그레체',
  'title_font_seed_id': None,
  'body_font_name': '고운돋움',
  'body_font_seed_id': None,
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '빙그레체의 명랑한 제목 자막과 고운돋움의 잔잔한 서브 자막.'},
 {'id': 26,
  'theme': '브이로그 자막',
  'title_font_name': '사진관',
  'title_font_seed_id': None,
  'body_font_name': '서울알림체',
  'body_font_seed_id': None,
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '사진관체의 손글씨 감성과 서울알림체의 또렷한 정보 전달력.'},
 {'id': 27,
  'theme': '브이로그 자막',
  'title_font_name': '온글잎 콘콘체',
  'title_font_seed_id': 68,
  'body_font_name': '나눔스퀘어',
  'body_font_seed_id': 23,
  'sample_title': '오늘의 브이로그',
  'sample_body': '아침 루틴부터 저녁 산책까지 함께해요.',
  'description': '콘콘체의 귀여운 손글씨와 나눔스퀘어의 깔끔함 — 다이어리 무드.'},
 {'id': 28,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Anton',
  'title_font_seed_id': 108,
  'body_font_name': '프리텐다드',
  'body_font_seed_id': 101,
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Anton의 압축된 임팩트 + 프리텐다드 한글 본문. 세일 배너의 정석.'},
 {'id': 29,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'Playfair Display',
  'title_font_seed_id': 139,
  'body_font_name': '나눔명조',
  'body_font_seed_id': 22,
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Playfair의 클래식한 세리프와 나눔명조 — 매거진, 웨딩, 고급 무드.'},
 {'id': 30,
  'theme': '한글 + 영문 조합',
  'title_font_name': 'DancingScript',
  'title_font_seed_id': 121,
  'body_font_name': '마루부리',
  'body_font_seed_id': 33,
  'sample_title': 'SUMMER SALE',
  'sample_body': '여름 신상품 최대 50% 할인, 7월 한정 진행됩니다.',
  'description': 'Dancing Script의 흐르는 필기체와 마루부리의 감성 본문.'}]
